Product:
  type: object
  documentation:
    en: "Any offered product or service. For example: a pair of shoes; a concert
      ticket; the rental of a car; a haircut; or an episode of a TV show
      streamed online."
  inherit: Thing
  properties:
    isAccessoryOrSparePartFor:
      type: Product
      documentation:
        en: A pointer to another product (or multiple products) for which this product
          is an accessory or spare part.
    hasAdultConsideration:
      type: AdultOrientedEnumeration
      documentation:
        en: Used to tag an item to be intended or suitable for consumption or use by
          adults only.
    gtin12:
      type: string
      documentation:
        en: The GTIN-12 code of the product, or the product to which the offer refers.
          The GTIN-12 is the 12-digit GS1 Identification Key composed of a
          U.P.C. Company Prefix, Item Reference, and Check Digit used to
          identify trade items. See [GS1 GTIN
          Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more
          details.
    nsn:
      type: string
      documentation:
        en: "Indicates the [NATO stock
          number](https://en.wikipedia.org/wiki/NATO_Stock_Number) (nsn) of a
          [[Product]]. "
    material:
      type:
        - string
        - string
        - Product
      documentation:
        en: A material that something is made from, e.g. leather, wool, cotton, paper.
    review:
      type: Review
      documentation:
        en: A review of the item.
    award:
      type: string
      documentation:
        en: An award won by or for this item.
    width:
      type:
        - QuantitativeValue
        - Distance
      documentation:
        en: The width of the item.
    countryOfOrigin:
      type: Country
      documentation:
        en: >-
          The country of origin of something, including products as well as
          creative  works such as movie and TV content.


          In the case of TV and movie, this would be the country of the principle offices of the production company or individual responsible for the movie. For other kinds of [[CreativeWork]] it is difficult to provide fully general guidance, and properties such as [[contentLocation]] and [[locationCreated]] may be more applicable.


          In the case of products, the country of origin of the product. The exact interpretation of this may vary by context and product type, and cannot be fully enumerated here.
    pattern:
      type:
        - DefinedTerm
        - string
      documentation:
        en: A pattern that something has, for example 'polka dot', 'striped', 'Canadian
          flag'. Values are typically expressed as text, although links to
          controlled value schemes are also supported.
    category:
      type:
        - string
        - string
        - PhysicalActivityCategory
        - Thing
        - CategoryCode
      documentation:
        en: A category for the item. Greater signs or slashes can be used to informally
          indicate a category hierarchy.
    funding:
      type: Grant
      documentation:
        en: A [[Grant]] that directly or indirectly provide funding or sponsorship for
          this item. See also [[ownershipFundingInfo]].
    mpn:
      type: string
      documentation:
        en: The Manufacturer Part Number (MPN) of the product, or the product to which
          the offer refers.
    height:
      type:
        - Distance
        - QuantitativeValue
      documentation:
        en: The height of the item.
    keywords:
      type:
        - DefinedTerm
        - string
        - string
      documentation:
        en: Keywords or tags used to describe some item. Multiple textual entries in a
          keywords list are typically delimited by commas, or by repeating the
          property.
    purchaseDate:
      type: date
      documentation:
        en: The date the item e.g. vehicle was purchased by the current owner.
    hasEnergyConsumptionDetails:
      type: EnergyConsumptionDetails
      documentation:
        en: Defines the energy efficiency Category (also known as "class" or "rating")
          for a product according to an international energy efficiency
          standard.
    audience:
      type: Audience
      documentation:
        en: An intended audience, i.e. a group for whom something was created.
    offers:
      type:
        - Offer
        - Demand
      documentation:
        en: "An offer to provide this item&#x2014;for example, an offer to sell a
          product, rent the DVD of a movie, perform a service, or give away
          tickets to an event. Use [[businessFunction]] to indicate the kind of
          transaction offered, i.e. sell, lease, etc. This property can also be
          used to describe a [[Demand]]. While this property is listed as
          expected on a number of common types, it can be used in others. In
          that case, using a second type, such as Product or a subtype of
          Product, can clarify the nature of the offer.

          \      "
    productionDate:
      type: date
      documentation:
        en: The date of production of the item, e.g. vehicle.
    itemCondition:
      type: OfferItemCondition
      documentation:
        en: A predefined value from OfferItemCondition specifying the condition of the
          product or service, or the products or services included in the offer.
          Also used for product return policies to specify the condition of
          products accepted for returns.
    awards:
      type: string
      documentation:
        en: Awards won by or for this item.
    gtin:
      type: string
      documentation:
        en: "A Global Trade Item Number
          ([GTIN](https://www.gs1.org/standards/id-keys/gtin)). GTINs identify
          trade items, including products and services, using numeric
          identification codes. The [[gtin]] property generalizes the earlier
          [[gtin8]], [[gtin12]], [[gtin13]], and [[gtin14]] properties. The GS1
          [digital link
          specifications](https://www.gs1.org/standards/Digital-Link/) express
          GTINs as URLs. A correct [[gtin]] value should be a valid GTIN, which
          means that it should be an all-numeric string of either 8, 12, 13 or
          14 digits, or a \"GS1 Digital Link\" URL based on such a string. The
          numeric component should also have a [valid GS1 check
          digit](https://www.gs1.org/services/check-digit-calculator) and meet
          the other rules for valid GTINs. See also [GS1's GTIN
          Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) and
          [Wikipedia](https://en.wikipedia.org/wiki/Global_Trade_Item_Number)
          for more details. Left-padding of the gtin values is not required or
          encouraged.

          \   "
    productID:
      type: string
      documentation:
        en: 'The product identifier, such as ISBN. For example: ``` meta
          itemprop="productID" content="isbn:123-456-789" ```.'
    countryOfAssembly:
      type: string
      documentation:
        en: The place where the product was assembled.
    color:
      type: string
      documentation:
        en: The color of the product.
    aggregateRating:
      type: AggregateRating
      documentation:
        en: The overall rating, based on a collection of reviews or ratings, of the
          item.
    isSimilarTo:
      type:
        - Service
        - Product
      documentation:
        en: A pointer to another, functionally similar product (or multiple products).
    depth:
      type:
        - Distance
        - QuantitativeValue
      documentation:
        en: The depth of the item.
    countryOfLastProcessing:
      type: string
      documentation:
        en: The place where the item (typically [[Product]]) was last processed and
          tested before importation.
    isVariantOf:
      type:
        - ProductModel
        - ProductGroup
      documentation:
        en: Indicates the kind of product that this is a variant of. In the case of
          [[ProductModel]], this is a pointer (from a ProductModel) to a base
          product from which this product is a variant. It is safe to infer that
          the variant inherits all product features from the base model, unless
          defined locally. This is not transitive. In the case of a
          [[ProductGroup]], the group description also serves as a template,
          representing a set of Products that vary on explicitly defined,
          specific dimensions only (so it defines both a set of variants, as
          well as which values distinguish amongst those variants). When used
          with [[ProductGroup]], this property can apply to any [[Product]]
          included in the group.
    slogan:
      type: string
      documentation:
        en: A slogan or motto associated with the item.
    brand:
      type:
        - Organization
        - Brand
      documentation:
        en: The brand(s) associated with a product or service, or the brand(s)
          maintained by an organization or business person.
    manufacturer:
      type: Organization
      documentation:
        en: The manufacturer of the product.
    hasMeasurement:
      type: QuantitativeValue
      documentation:
        en: A product measurement, for example the inseam of pants, the wheel size of a
          bicycle, or the gauge of a screw. Usually an exact measurement, but
          can also be a range of measurements for adjustable products, for
          example belts and ski bindings.
    isConsumableFor:
      type: Product
      documentation:
        en: A pointer to another product (or multiple products) for which this product
          is a consumable.
    logo:
      type:
        - string
        - ImageObject
      documentation:
        en: An associated logo.
    gtin8:
      type: string
      documentation:
        en: The GTIN-8 code of the product, or the product to which the offer refers.
          This code is also known as EAN/UCC-8 or 8-digit EAN. See [GS1 GTIN
          Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more
          details.
    sku:
      type: string
      documentation:
        en: The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier for a
          product or service, or the product to which the offer refers.
    inProductGroupWithID:
      type: string
      documentation:
        en: "Indicates the [[productGroupID]] for a [[ProductGroup]] that this product
          [[isVariantOf]]. "
    model:
      type:
        - ProductModel
        - string
      documentation:
        en: The model of the product. Use with the URL of a ProductModel or a textual
          representation of the model identifier. The URL of the ProductModel
          can be from an external source. It is recommended to additionally
          provide strong product identifiers via the gtin8/gtin13/gtin14 and mpn
          properties.
    hasMerchantReturnPolicy:
      type: MerchantReturnPolicy
      documentation:
        en: Specifies a MerchantReturnPolicy that may be applicable.
    releaseDate:
      type: date
      documentation:
        en: The release date of a product or product model. This can be used to
          distinguish the exact variant of a product.
    gtin14:
      type: string
      documentation:
        en: The GTIN-14 code of the product, or the product to which the offer refers.
          See [GS1 GTIN
          Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more
          details.
    weight:
      type: QuantitativeValue
      documentation:
        en: The weight of the product or person.
    size:
      type:
        - QuantitativeValue
        - DefinedTerm
        - string
        - SizeSpecification
      documentation:
        en: "A standardized size of a product or creative work, specified either through
          a simple textual string (for example 'XL', '32Wx34L'),
          a  QuantitativeValue with a unitCode, or a comprehensive and
          structured [[SizeSpecification]]; in other cases, the [[width]],
          [[height]], [[depth]] and [[weight]] properties may be more
          applicable. "
    additionalProperty:
      type: PropertyValue
      documentation:
        en: >
          A property-value pair representing an additional characteristics of the
          entitity, e.g. a product feature or another characteristic for which
          there is no matching property in schema.org.\n\nNote: Publishers
          should be aware that applications designed to use specific schema.org
          properties (e.g. https://schema.org/width, https://schema.org/color,
          https://schema.org/gtin13, ...) will typically expect such data to be
          provided using those properties, rather than using the generic
          property/value mechanism.
    gtin13:
      type: string
      documentation:
        en: The GTIN-13 code of the product, or the product to which the offer refers.
          This is equivalent to 13-digit ISBN codes and EAN UCC-13. Former
          12-digit UPC codes can be converted into a GTIN-13 code by simply
          adding a preceding zero. See [GS1 GTIN
          Summary](http://www.gs1.org/barcodes/technical/idkeys/gtin) for more
          details.
    reviews:
      type: Review
      documentation:
        en: Review of the item.
    isFamilyFriendly:
      type: boolean
      documentation:
        en: Indicates whether this content is family friendly.
    isRelatedTo:
      type:
        - Service
        - Product
      documentation:
        en: A pointer to another, somehow related product (or multiple products).
