classDiagram
  ActionAccessSpecification -- Offer
  ActionAccessSpecification -- PhysicalActivityCategory
  ActionAccessSpecification -- Thing
  ActionAccessSpecification -- CategoryCode
  ActionAccessSpecification -- Place
  ActionAccessSpecification -- GeoShape
  ActionAccessSpecification -- MediaSubscription
  ActionAccessSpecification -- date
  ActionAccessSpecification -- dateTime
  ActionAccessSpecification -- time


class ActionAccessSpecification {

  Offer expectsAcceptanceOf
  string category
  string category
  PhysicalActivityCategory category
  Thing category
  CategoryCode category
  Place ineligibleRegion
  string ineligibleRegion
  GeoShape ineligibleRegion
  MediaSubscription requiresSubscription
  boolean requiresSubscription
  date availabilityEnds
  dateTime availabilityEnds
  time availabilityEnds
  GeoShape eligibleRegion
  string eligibleRegion
  Place eligibleRegion
  time availabilityStarts
  dateTime availabilityStarts
  date availabilityStarts

 }
