classDiagram
  AggregateOffer -- Offer
  AggregateOffer -- Demand


class AggregateOffer {

  string highPrice
  number highPrice
  Offer offers
  Demand offers
  string lowPrice
  number lowPrice
  number offerCount

 }
