classDiagram
  Book -- Person
  Book -- BookFormatType


class Book {

  string isbn
  Person illustrator
  number numberOfPages
  boolean abridged
  BookFormatType bookFormat
  string bookEdition

 }
