classDiagram
  BroadcastChannel -- BroadcastFrequencySpecification
  BroadcastChannel -- BroadcastService
  BroadcastChannel -- CableOrSatelliteService


class BroadcastChannel {

  string genre
  string genre
  BroadcastFrequencySpecification broadcastFrequency
  string broadcastFrequency
  BroadcastService providesBroadcastService
  string broadcastChannelId
  CableOrSatelliteService inBroadcastLineup
  string broadcastServiceTier

 }
