classDiagram
  BusTrip -- BusStop
  BusTrip -- BusStation


class BusTrip {

  BusStop departureBusStop
  BusStation departureBusStop
  string busName
  BusStation arrivalBusStop
  BusStop arrivalBusStop
  string busNumber

 }
