classDiagram
  Clip -- HyperTocEntry
  Clip -- Person
  Clip -- Episode
  Clip -- CreativeWorkSeries
  Clip -- CreativeWorkSeason
  Clip -- MusicGroup


class Clip {

  number startOffset
  HyperTocEntry startOffset
  number endOffset
  HyperTocEntry endOffset
  Person director
  Person actor
  Episode partOfEpisode
  string clipNumber
  number clipNumber
  CreativeWorkSeries partOfSeries
  CreativeWorkSeason partOfSeason
  Person actors
  Person musicBy
  MusicGroup musicBy
  Person directors

 }
