classDiagram
  CookAction -- Recipe
  CookAction -- Place
  CookAction -- FoodEstablishment
  CookAction -- FoodEvent


class CookAction {

  Recipe recipe
  Place foodEstablishment
  FoodEstablishment foodEstablishment
  FoodEvent foodEvent

 }
