classDiagram
  Course -- AlignmentObject
  Course -- Course
  Course -- EducationalOccupationalCredential
  Course -- StructuredValue
  Course -- CourseInstance


class Course {

  string coursePrerequisites
  AlignmentObject coursePrerequisites
  Course coursePrerequisites
  string educationalCredentialAwarded
  EducationalOccupationalCredential educationalCredentialAwarded
  string educationalCredentialAwarded
  number numberOfCredits
  StructuredValue numberOfCredits
  EducationalOccupationalCredential occupationalCredentialAwarded
  string occupationalCredentialAwarded
  string occupationalCredentialAwarded
  string courseCode
  CourseInstance hasCourseInstance

 }
