classDiagram
  DataFeedItem -- dateTime
  DataFeedItem -- date
  DataFeedItem -- Thing


class DataFeedItem {

  dateTime dateDeleted
  date dateDeleted
  date dateCreated
  dateTime dateCreated
  dateTime dateModified
  date dateModified
  Thing item

 }
