classDiagram
  DefinedRegion -- Country
  DefinedRegion -- PostalCodeRangeSpecification


class DefinedRegion {

  Country addressCountry
  string addressCountry
  string addressRegion
  PostalCodeRangeSpecification postalCodeRange
  string postalCodePrefix
  string postalCode

 }
