classDiagram
  DeliveryEvent -- dateTime
  DeliveryEvent -- DeliveryMethod


class DeliveryEvent {

  string accessCode
  dateTime availableThrough
  DeliveryMethod hasDeliveryMethod
  dateTime availableFrom

 }
