classDiagram
  Demand -- Trip
  Demand -- Event
  Demand -- Product
  Demand -- AggregateOffer
  Demand -- CreativeWork
  Demand -- MenuItem
  Demand -- Service
  Demand -- TypeAndQuantityNode
  Demand -- BusinessFunction
  Demand -- OfferItemCondition
  Demand -- QuantitativeValue
  Demand -- LoanOrCredit
  Demand -- PaymentMethod
  Demand -- WarrantyPromise
  Demand -- Organization
  Demand -- Person
  Demand -- Place
  Demand -- GeoShape
  Demand -- DeliveryMethod
  Demand -- dateTime
  Demand -- date
  Demand -- time
  Demand -- PriceSpecification
  Demand -- AdministrativeArea
  Demand -- BusinessEntityType
  Demand -- ItemAvailability


class Demand {

  string gtin12
  Trip itemOffered
  Event itemOffered
  Product itemOffered
  AggregateOffer itemOffered
  CreativeWork itemOffered
  MenuItem itemOffered
  Service itemOffered
  string mpn
  TypeAndQuantityNode includesObject
  BusinessFunction businessFunction
  OfferItemCondition itemCondition
  string gtin
  QuantitativeValue eligibleQuantity
  LoanOrCredit acceptedPaymentMethod
  PaymentMethod acceptedPaymentMethod
  WarrantyPromise warranty
  Organization seller
  Person seller
  Place ineligibleRegion
  string ineligibleRegion
  GeoShape ineligibleRegion
  QuantitativeValue deliveryLeadTime
  DeliveryMethod availableDeliveryMethod
  dateTime validFrom
  date validFrom
  date availabilityEnds
  dateTime availabilityEnds
  time availabilityEnds
  GeoShape eligibleRegion
  string eligibleRegion
  Place eligibleRegion
  string gtin8
  QuantitativeValue inventoryLevel
  string sku
  QuantitativeValue advanceBookingRequirement
  string gtin14
  PriceSpecification eligibleTransactionVolume
  AdministrativeArea areaServed
  GeoShape areaServed
  string areaServed
  Place areaServed
  BusinessEntityType eligibleCustomerType
  ItemAvailability availability
  string gtin13
  dateTime validThrough
  date validThrough
  PriceSpecification priceSpecification
  time availabilityStarts
  dateTime availabilityStarts
  date availabilityStarts
  QuantitativeValue eligibleDuration
  Place availableAtOrFrom
  string serialNumber

 }
