classDiagram
  Diet -- Person
  Diet -- Organization


class Diet {

  string expertConsiderations
  string risks
  string physiologicalBenefits
  Person endorsers
  Organization endorsers
  string dietFeatures

 }
