classDiagram
  DietarySupplement -- RecommendedDoseSchedule
  DietarySupplement -- DrugLegalStatus
  DietarySupplement -- MedicalEnumeration
  DietarySupplement -- MaximumDoseSchedule
  DietarySupplement -- Organization


class DietarySupplement {

  string targetPopulation
  RecommendedDoseSchedule recommendedIntake
  DrugLegalStatus legalStatus
  string legalStatus
  MedicalEnumeration legalStatus
  string mechanismOfAction
  MaximumDoseSchedule maximumIntake
  string activeIngredient
  string proprietaryName
  string nonProprietaryName
  Organization manufacturer
  boolean isProprietary
  string safetyConsideration

 }
