classDiagram
  DrugCost -- AdministrativeArea
  DrugCost -- QualitativeValue
  DrugCost -- DrugCostCategory


class DrugCost {

  AdministrativeArea applicableLocation
  number costPerUnit
  string costPerUnit
  QualitativeValue costPerUnit
  DrugCostCategory costCategory
  string drugUnit
  string costCurrency
  string costOrigin

 }
