classDiagram
  EmployeeRole -- PriceSpecification
  EmployeeRole -- MonetaryAmount


class EmployeeRole {

  string salaryCurrency
  number baseSalary
  PriceSpecification baseSalary
  MonetaryAmount baseSalary

 }
