classDiagram
  EnergyConsumptionDetails -- EUEnergyEfficiencyEnumeration
  EnergyConsumptionDetails -- EnergyEfficiencyEnumeration


class EnergyConsumptionDetails {

  EUEnergyEfficiencyEnumeration energyEfficiencyScaleMin
  EnergyEfficiencyEnumeration hasEnergyEfficiencyCategory
  EUEnergyEfficiencyEnumeration energyEfficiencyScaleMax

 }
