classDiagram
  EngineSpecification -- QualitativeValue
  EngineSpecification -- QuantitativeValue


class EngineSpecification {

  string fuelType
  string fuelType
  QualitativeValue fuelType
  QuantitativeValue torque
  QuantitativeValue engineDisplacement
  QuantitativeValue enginePower
  QualitativeValue engineType
  string engineType
  string engineType

 }
