classDiagram
  Episode -- Person
  Episode -- VideoObject
  Episode -- CreativeWorkSeries
  Episode -- Duration
  Episode -- CreativeWorkSeason
  Episode -- Organization
  Episode -- MusicGroup


class Episode {

  number episodeNumber
  string episodeNumber
  Person director
  Person actor
  VideoObject trailer
  CreativeWorkSeries partOfSeries
  Duration duration
  CreativeWorkSeason partOfSeason
  Organization productionCompany
  Person actors
  Person musicBy
  MusicGroup musicBy
  Person directors

 }
