classDiagram
  FinancialProduct -- QuantitativeValue


class FinancialProduct {

  number annualPercentageRate
  QuantitativeValue annualPercentageRate
  string feesAndCommissionsSpecification
  string feesAndCommissionsSpecification
  number interestRate
  QuantitativeValue interestRate

 }
