classDiagram
  FlightReservation -- QualitativeValue


class FlightReservation {

  QualitativeValue passengerPriorityStatus
  string passengerPriorityStatus
  string boardingGroup
  string securityScreening
  string passengerSequenceNumber

 }
