classDiagram
  FloorPlan -- Accommodation
  FloorPlan -- QuantitativeValue
  FloorPlan -- LocationFeatureSpecification
  FloorPlan -- ImageObject


class FloorPlan {

  Accommodation isPlanForApartment
  number numberOfBathroomsTotal
  QuantitativeValue numberOfRooms
  number numberOfRooms
  QuantitativeValue numberOfAccommodationUnits
  QuantitativeValue numberOfAvailableAccommodationUnits
  LocationFeatureSpecification amenityFeature
  number numberOfBedrooms
  QuantitativeValue numberOfBedrooms
  number numberOfPartialBathrooms
  QuantitativeValue floorSize
  number numberOfFullBathrooms
  string petsAllowed
  boolean petsAllowed
  ImageObject layoutImage
  string layoutImage

 }
