classDiagram
  FoodEstablishment -- Rating
  FoodEstablishment -- Menu


class FoodEstablishment {

  Rating starRating
  string servesCuisine
  string acceptsReservations
  boolean acceptsReservations
  string acceptsReservations
  string hasMenu
  string hasMenu
  Menu hasMenu
  string menu
  Menu menu
  string menu

 }
