classDiagram
  Game -- Thing
  Game -- QuantitativeValue
  Game -- Place
  Game -- PostalAddress


class Game {

  Thing characterAttribute
  Thing gameItem
  QuantitativeValue numberOfPlayers
  Thing quest
  Place gameLocation
  string gameLocation
  PostalAddress gameLocation

 }
