classDiagram
  GeoShape -- Country
  GeoShape -- PostalAddress


class GeoShape {

  Country addressCountry
  string addressCountry
  string circle
  string line
  string polygon
  string address
  PostalAddress address
  string postalCode
  string elevation
  number elevation
  string box

 }
