classDiagram
  Grant -- Organization
  Grant -- Person
  Grant -- Product
  Grant -- BioChemEntity
  Grant -- Event
  Grant -- MedicalEntity
  Grant -- CreativeWork


class Grant {

  Organization funder
  Person funder
  Product fundedItem
  Person fundedItem
  BioChemEntity fundedItem
  Event fundedItem
  MedicalEntity fundedItem
  CreativeWork fundedItem
  Organization fundedItem
  Organization sponsor
  Person sponsor

 }
