classDiagram
  HowToDirection -- MediaObject
  HowToDirection -- HowToSupply
  HowToDirection -- Duration
  HowToDirection -- HowToTool


class HowToDirection {

  string afterMedia
  MediaObject afterMedia
  HowToSupply supply
  string supply
  string duringMedia
  MediaObject duringMedia
  Duration totalTime
  string beforeMedia
  MediaObject beforeMedia
  HowToTool tool
  string tool
  Duration prepTime
  Duration performTime

 }
