classDiagram
  HowTo -- QuantitativeValue
  HowTo -- MonetaryAmount
  HowTo -- HowToSupply
  HowTo -- HowToStep
  HowTo -- HowToSection
  HowTo -- CreativeWork
  HowTo -- Duration
  HowTo -- HowToTool
  HowTo -- ItemList


class HowTo {

  string yield
  QuantitativeValue yield
  string estimatedCost
  MonetaryAmount estimatedCost
  HowToSupply supply
  string supply
  HowToStep step
  HowToSection step
  string step
  CreativeWork step
  Duration totalTime
  HowToTool tool
  string tool
  Duration prepTime
  ItemList steps
  CreativeWork steps
  string steps
  Duration performTime

 }
