classDiagram
  Invoice -- MonetaryAmount
  Invoice -- PriceSpecification
  Invoice -- Duration
  Invoice -- Order
  Invoice -- PhysicalActivityCategory
  Invoice -- Thing
  Invoice -- CategoryCode
  Invoice -- date
  Invoice -- Organization
  Invoice -- Person
  Invoice -- dateTime
  Invoice -- PaymentStatusType
  Invoice -- PaymentMethod


class Invoice {

  MonetaryAmount totalPaymentDue
  PriceSpecification totalPaymentDue
  Duration billingPeriod
  Order referencesOrder
  string accountId
  string category
  string category
  PhysicalActivityCategory category
  Thing category
  CategoryCode category
  date scheduledPaymentDate
  string confirmationNumber
  Organization customer
  Person customer
  Organization provider
  Person provider
  MonetaryAmount minimumPaymentDue
  PriceSpecification minimumPaymentDue
  dateTime paymentDueDate
  date paymentDueDate
  Person broker
  Organization broker
  PaymentStatusType paymentStatus
  string paymentStatus
  string paymentMethodId
  dateTime paymentDue
  PaymentMethod paymentMethod

 }
