classDiagram
  ItemList -- Thing
  ItemList -- ListItem
  ItemList -- ItemListOrderType


class ItemList {

  number numberOfItems
  Thing itemListElement
  ListItem itemListElement
  string itemListElement
  string itemListOrder
  ItemListOrderType itemListOrder

 }
