classDiagram
  JobPosting -- MonetaryAmountDistribution
  JobPosting -- MonetaryAmount
  JobPosting -- Place
  JobPosting -- DefinedTerm
  JobPosting -- AdministrativeArea
  JobPosting -- date
  JobPosting -- ContactPoint
  JobPosting -- Occupation
  JobPosting -- OccupationalExperienceRequirements
  JobPosting -- EducationalOccupationalCredential
  JobPosting -- PriceSpecification
  JobPosting -- dateTime
  JobPosting -- Organization
  JobPosting -- CategoryCode


class JobPosting {

  string employerOverview
  MonetaryAmountDistribution estimatedSalary
  MonetaryAmount estimatedSalary
  number estimatedSalary
  string jobLocationType
  string responsibilities
  Place jobLocation
  string physicalRequirement
  string physicalRequirement
  DefinedTerm physicalRequirement
  string incentives
  boolean directApply
  DefinedTerm sensoryRequirement
  string sensoryRequirement
  string sensoryRequirement
  AdministrativeArea applicantLocationRequirements
  string workHours
  date jobStartDate
  string jobStartDate
  string employmentType
  string specialCommitments
  ContactPoint applicationContact
  string incentiveCompensation
  Occupation relevantOccupation
  number totalJobOpenings
  string experienceRequirements
  OccupationalExperienceRequirements experienceRequirements
  string jobBenefits
  string salaryCurrency
  boolean experienceInPlaceOfEducation
  string securityClearanceRequirement
  string securityClearanceRequirement
  string eligibilityToWorkRequirement
  EducationalOccupationalCredential educationRequirements
  string educationRequirements
  string benefits
  DefinedTerm industry
  string industry
  number baseSalary
  PriceSpecification baseSalary
  MonetaryAmount baseSalary
  date datePosted
  dateTime datePosted
  string skills
  DefinedTerm skills
  string title
  Organization hiringOrganization
  boolean jobImmediateStart
  dateTime validThrough
  date validThrough
  Organization employmentUnit
  string qualifications
  EducationalOccupationalCredential qualifications
  CategoryCode occupationalCategory
  string occupationalCategory

 }
