classDiagram
  LearningResource -- DefinedTerm
  LearningResource -- AlignmentObject


class LearningResource {

  DefinedTerm teaches
  string teaches
  string educationalLevel
  DefinedTerm educationalLevel
  string educationalLevel
  string assesses
  DefinedTerm assesses
  DefinedTerm educationalUse
  string educationalUse
  AlignmentObject educationalAlignment
  string competencyRequired
  DefinedTerm competencyRequired
  string competencyRequired
  DefinedTerm learningResourceType
  string learningResourceType

 }
