classDiagram
  LocationFeatureSpecification -- OpeningHoursSpecification
  LocationFeatureSpecification -- dateTime
  LocationFeatureSpecification -- date


class LocationFeatureSpecification {

  OpeningHoursSpecification hoursAvailable
  dateTime validFrom
  date validFrom
  dateTime validThrough
  date validThrough

 }
