classDiagram
  LodgingBusiness -- QuantitativeValue
  LodgingBusiness -- Audience
  LodgingBusiness -- Rating
  LodgingBusiness -- LocationFeatureSpecification
  LodgingBusiness -- Language
  LodgingBusiness -- dateTime
  LodgingBusiness -- time


class LodgingBusiness {

  QuantitativeValue numberOfRooms
  number numberOfRooms
  Audience audience
  Rating starRating
  LocationFeatureSpecification amenityFeature
  string availableLanguage
  Language availableLanguage
  dateTime checkoutTime
  time checkoutTime
  dateTime checkinTime
  time checkinTime
  string petsAllowed
  boolean petsAllowed

 }
