classDiagram
  MedicalStudy -- MedicalCondition
  MedicalStudy -- EventStatusType
  MedicalStudy -- MedicalStudyStatus
  MedicalStudy -- MedicalEntity
  MedicalStudy -- AdministrativeArea
  MedicalStudy -- Organization
  MedicalStudy -- Person


class MedicalStudy {

  MedicalCondition healthCondition
  string status
  EventStatusType status
  MedicalStudyStatus status
  MedicalEntity studySubject
  AdministrativeArea studyLocation
  Organization sponsor
  Person sponsor

 }
