classDiagram
  MedicalCondition -- MedicalTherapy
  MedicalCondition -- EventStatusType
  MedicalCondition -- MedicalStudyStatus
  MedicalCondition -- DDxElement
  MedicalCondition -- MedicalConditionStage
  MedicalCondition -- Drug
  MedicalCondition -- AnatomicalStructure
  MedicalCondition -- AnatomicalSystem
  MedicalCondition -- SuperficialAnatomy
  MedicalCondition -- MedicalSignOrSymptom
  MedicalCondition -- MedicalTest
  MedicalCondition -- MedicalRiskFactor


class MedicalCondition {

  string possibleComplication
  string naturalProgression
  MedicalTherapy primaryPrevention
  string status
  EventStatusType status
  MedicalStudyStatus status
  DDxElement differentialDiagnosis
  MedicalConditionStage stage
  string pathophysiology
  Drug drug
  MedicalTherapy secondaryPrevention
  AnatomicalStructure associatedAnatomy
  AnatomicalSystem associatedAnatomy
  SuperficialAnatomy associatedAnatomy
  MedicalSignOrSymptom signOrSymptom
  MedicalTest typicalTest
  string epidemiology
  MedicalRiskFactor riskFactor
  string expectedPrognosis
  MedicalTherapy possibleTreatment

 }
