classDiagram
  MedicalSpecialty -- MedicalSpecialty


class MedicalSpecialty {

  MedicalSpecialty Cardiovascular
  MedicalSpecialty Renal
  MedicalSpecialty Nursing
  MedicalSpecialty Dermatologic
  MedicalSpecialty DietNutrition
  MedicalSpecialty PrimaryCare
  MedicalSpecialty Oncologic
  MedicalSpecialty Physiotherapy
  MedicalSpecialty Optometric
  MedicalSpecialty Gynecologic
  MedicalSpecialty Midwifery
  MedicalSpecialty SpeechPathology
  MedicalSpecialty CommunityHealth
  MedicalSpecialty Emergency
  MedicalSpecialty LaboratoryScience
  MedicalSpecialty Geriatric
  MedicalSpecialty Anesthesia
  MedicalSpecialty Endocrine
  MedicalSpecialty RespiratoryTherapy
  MedicalSpecialty Pediatric
  MedicalSpecialty Genetic
  MedicalSpecialty Infectious
  MedicalSpecialty Rheumatologic
  MedicalSpecialty Musculoskeletal
  MedicalSpecialty Podiatric
  MedicalSpecialty Obstetric
  MedicalSpecialty Pathology
  MedicalSpecialty Pulmonary
  MedicalSpecialty Dermatology
  MedicalSpecialty Dentistry
  MedicalSpecialty Gastroenterologic
  MedicalSpecialty PublicHealth
  MedicalSpecialty Psychiatric
  MedicalSpecialty PharmacySpecialty
  MedicalSpecialty Hematologic
  MedicalSpecialty Toxicologic
  MedicalSpecialty PlasticSurgery
  MedicalSpecialty Urologic
  MedicalSpecialty Neurologic
  MedicalSpecialty Otolaryngologic
  MedicalSpecialty Surgical

 }
