classDiagram
  MediaObject -- QuantitativeValue
  MediaObject -- Distance
  MediaObject -- Place
  MediaObject -- dateTime
  MediaObject -- time
  MediaObject -- NewsArticle
  MediaObject -- GeoShape
  MediaObject -- MediaSubscription
  MediaObject -- CreativeWork
  MediaObject -- Duration
  MediaObject -- date
  MediaObject -- Organization
  MediaObject -- Claim


class MediaObject {

  string contentSize
  string contentUrl
  QuantitativeValue width
  Distance width
  Distance height
  QuantitativeValue height
  Place regionsAllowed
  dateTime startTime
  time startTime
  NewsArticle associatedArticle
  Place ineligibleRegion
  string ineligibleRegion
  GeoShape ineligibleRegion
  MediaSubscription requiresSubscription
  boolean requiresSubscription
  string playerType
  CreativeWork encodesCreativeWork
  Duration duration
  string encodingFormat
  string encodingFormat
  date uploadDate
  string embedUrl
  string bitrate
  dateTime endTime
  time endTime
  Organization productionCompany
  string sha256
  Claim interpretedAsClaim

 }
