classDiagram
  MedicalRiskEstimator -- MedicalEntity
  MedicalRiskEstimator -- MedicalRiskFactor


class MedicalRiskEstimator {

  MedicalEntity estimatesRiskOf
  MedicalRiskFactor includedRiskFactor

 }
