classDiagram
  class MediaManipulationRatingEnumeration {
<<enumeration>>
  o OriginalMediaContent
  o SatireOrParodyContent
  o EditedOrCroppedContent
  o DecontextualizedContent
  o . . . 2 more values
 }
