classDiagram
  MedicalWebPage -- MedicalAudienceType
  MedicalWebPage -- MedicalAudience


class MedicalWebPage {

  string aspect
  MedicalAudienceType medicalAudience
  MedicalAudience medicalAudience

 }
