classDiagram
  MedicalProcedure -- MedicalProcedureType
  MedicalProcedure -- MedicalEntity
  MedicalProcedure -- EventStatusType
  MedicalProcedure -- MedicalStudyStatus


class MedicalProcedure {

  MedicalProcedureType procedureType
  MedicalEntity preparation
  string preparation
  string bodyLocation
  string status
  EventStatusType status
  MedicalStudyStatus status
  string howPerformed
  string followup

 }
