classDiagram
  MerchantReturnPolicy -- MerchantReturnEnumeration
  MerchantReturnPolicy -- Country
  MerchantReturnPolicy -- MonetaryAmount
  MerchantReturnPolicy -- ReturnFeesEnumeration
  MerchantReturnPolicy -- OfferItemCondition
  MerchantReturnPolicy -- ReturnLabelSourceEnumeration
  MerchantReturnPolicy -- RefundTypeEnumeration
  MerchantReturnPolicy -- dateTime
  MerchantReturnPolicy -- date
  MerchantReturnPolicy -- ReturnMethodEnumeration
  MerchantReturnPolicy -- PropertyValue
  MerchantReturnPolicy -- MerchantReturnPolicySeasonalOverride


class MerchantReturnPolicy {

  MerchantReturnEnumeration returnPolicyCategory
  Country returnPolicyCountry
  string returnPolicyCountry
  string merchantReturnLink
  MonetaryAmount restockingFee
  number restockingFee
  MonetaryAmount itemDefectReturnShippingFeesAmount
  ReturnFeesEnumeration itemDefectReturnFees
  boolean inStoreReturnsOffered
  OfferItemCondition itemCondition
  ReturnLabelSourceEnumeration itemDefectReturnLabelSource
  ReturnLabelSourceEnumeration returnLabelSource
  MonetaryAmount customerRemorseReturnShippingFeesAmount
  RefundTypeEnumeration refundType
  MonetaryAmount returnShippingFeesAmount
  dateTime merchantReturnDays
  number merchantReturnDays
  date merchantReturnDays
  ReturnMethodEnumeration returnMethod
  PropertyValue additionalProperty
  ReturnLabelSourceEnumeration customerRemorseReturnLabelSource
  ReturnFeesEnumeration customerRemorseReturnFees
  MerchantReturnPolicySeasonalOverride returnPolicySeasonalOverride
  string applicableCountry
  Country applicableCountry
  ReturnFeesEnumeration returnFees

 }
