classDiagram
  MerchantReturnPolicySeasonalOverride -- MerchantReturnEnumeration
  MerchantReturnPolicySeasonalOverride -- dateTime
  MerchantReturnPolicySeasonalOverride -- date


class MerchantReturnPolicySeasonalOverride {

  MerchantReturnEnumeration returnPolicyCategory
  dateTime startDate
  date startDate
  date endDate
  dateTime endDate
  dateTime merchantReturnDays
  number merchantReturnDays
  date merchantReturnDays

 }
