classDiagram
  MolecularEntity -- QuantitativeValue
  MolecularEntity -- DefinedTerm


class MolecularEntity {

  string inChIKey
  string iupacName
  string monoisotopicMolecularWeight
  QuantitativeValue monoisotopicMolecularWeight
  string molecularFormula
  DefinedTerm potentialUse
  DefinedTerm chemicalRole
  QuantitativeValue molecularWeight
  string molecularWeight
  string inChI
  string smiles

 }
