classDiagram
  MonetaryGrant -- Organization
  MonetaryGrant -- Person
  MonetaryGrant -- MonetaryAmount


class MonetaryGrant {

  Organization funder
  Person funder
  number amount
  MonetaryAmount amount

 }
