classDiagram
  MoneyTransfer -- BankOrCreditUnion
  MoneyTransfer -- MonetaryAmount


class MoneyTransfer {

  BankOrCreditUnion beneficiaryBank
  string beneficiaryBank
  number amount
  MonetaryAmount amount

 }
