classDiagram
  MovieSeries -- Person
  MovieSeries -- VideoObject
  MovieSeries -- Organization
  MovieSeries -- MusicGroup


class MovieSeries {

  Person director
  Person actor
  VideoObject trailer
  Organization productionCompany
  Person actors
  Person musicBy
  MusicGroup musicBy
  Person directors

 }
