classDiagram
  Movie -- Country
  Movie -- Person
  Movie -- Language
  Movie -- VideoObject
  Movie -- Duration
  Movie -- Organization
  Movie -- MusicGroup


class Movie {

  Country countryOfOrigin
  Person director
  string titleEIDR
  string titleEIDR
  Language subtitleLanguage
  string subtitleLanguage
  Person actor
  VideoObject trailer
  Duration duration
  Organization productionCompany
  Person actors
  Person musicBy
  MusicGroup musicBy
  Person directors

 }
