classDiagram
  MusicRelease -- MusicAlbum
  MusicRelease -- MusicReleaseFormatType
  MusicRelease -- Duration
  MusicRelease -- Person
  MusicRelease -- Organization


class MusicRelease {

  MusicAlbum releaseOf
  MusicReleaseFormatType musicReleaseFormat
  Duration duration
  Person creditedTo
  Organization creditedTo
  Organization recordLabel
  string catalogNumber

 }
