classDiagram
  MusicRecording -- MusicPlaylist
  MusicRecording -- MusicAlbum
  MusicRecording -- MusicComposition
  MusicRecording -- Duration
  MusicRecording -- Person
  MusicRecording -- MusicGroup


class MusicRecording {

  string isrcCode
  MusicPlaylist inPlaylist
  MusicAlbum inAlbum
  MusicComposition recordingOf
  Duration duration
  Person byArtist
  MusicGroup byArtist

 }
