classDiagram
  NewsMediaOrganization -- AboutPage
  NewsMediaOrganization -- CreativeWork
  NewsMediaOrganization -- Article


class NewsMediaOrganization {

  string ownershipFundingInfo
  AboutPage ownershipFundingInfo
  string ownershipFundingInfo
  CreativeWork ownershipFundingInfo
  string correctionsPolicy
  CreativeWork correctionsPolicy
  string diversityStaffingReport
  Article diversityStaffingReport
  CreativeWork diversityPolicy
  string diversityPolicy
  string ethicsPolicy
  CreativeWork ethicsPolicy
  CreativeWork missionCoveragePrioritiesPolicy
  string missionCoveragePrioritiesPolicy
  string actionableFeedbackPolicy
  CreativeWork actionableFeedbackPolicy
  string masthead
  CreativeWork masthead
  CreativeWork unnamedSourcesPolicy
  string unnamedSourcesPolicy
  string verificationFactCheckingPolicy
  CreativeWork verificationFactCheckingPolicy
  CreativeWork noBylinesPolicy
  string noBylinesPolicy

 }
