classDiagram
  Occupation -- MonetaryAmountDistribution
  Occupation -- MonetaryAmount
  Occupation -- AdministrativeArea
  Occupation -- OccupationalExperienceRequirements
  Occupation -- EducationalOccupationalCredential
  Occupation -- DefinedTerm
  Occupation -- CategoryCode


class Occupation {

  MonetaryAmountDistribution estimatedSalary
  MonetaryAmount estimatedSalary
  number estimatedSalary
  string responsibilities
  AdministrativeArea occupationLocation
  string experienceRequirements
  OccupationalExperienceRequirements experienceRequirements
  EducationalOccupationalCredential educationRequirements
  string educationRequirements
  string skills
  DefinedTerm skills
  string qualifications
  EducationalOccupationalCredential qualifications
  CategoryCode occupationalCategory
  string occupationalCategory

 }
