classDiagram
  OpeningHoursSpecification -- time
  OpeningHoursSpecification -- DayOfWeek
  OpeningHoursSpecification -- dateTime
  OpeningHoursSpecification -- date


class OpeningHoursSpecification {

  time closes
  DayOfWeek dayOfWeek
  dateTime validFrom
  date validFrom
  time opens
  dateTime validThrough
  date validThrough

 }
