classDiagram
  Operation -- Operation, Variable, number
  Operation -- OperandEnum


class Operation {

  Operation, Variable, number leftHand
  OperandEnum operand
  Operation, Variable, number rightHand

 }
