classDiagram
  Organization -- AboutPage
  Organization -- CreativeWork
  Organization -- EducationalOccupationalCredential
  Organization -- Person
  Organization -- Review
  Organization -- Thing
  Organization -- Organization
  Organization -- date
  Organization -- Grant
  Organization -- DefinedTerm
  Organization -- ContactPoint
  Organization -- QuantitativeValue
  Organization -- Offer
  Organization -- AggregateRating
  Organization -- InteractionCounter
  Organization -- PostalAddress
  Organization -- Place
  Organization -- VirtualLocation
  Organization -- ProgramMembership
  Organization -- Article
  Organization -- NonprofitType
  Organization -- Brand
  Organization -- ImageObject
  Organization -- GeoShape
  Organization -- AdministrativeArea
  Organization -- MerchantReturnPolicy
  Organization -- Language
  Organization -- Demand
  Organization -- Product
  Organization -- OwnershipInfo
  Organization -- OfferCatalog
  Organization -- Event


class Organization {

  string ownershipFundingInfo
  AboutPage ownershipFundingInfo
  string ownershipFundingInfo
  CreativeWork ownershipFundingInfo
  EducationalOccupationalCredential hasCredential
  Person founders
  string telephone
  Review review
  string knowsAbout
  string knowsAbout
  Thing knowsAbout
  string award
  Organization member
  Person member
  Person employee
  date dissolutionDate
  Grant funding
  string vatID
  string globalLocationNumber
  DefinedTerm keywords
  string keywords
  string keywords
  ContactPoint contactPoints
  Organization subOrganization
  string awards
  QuantitativeValue numberOfEmployees
  Organization funder
  Person funder
  Offer makesOffer
  string legalName
  string correctionsPolicy
  CreativeWork correctionsPolicy
  AggregateRating aggregateRating
  InteractionCounter interactionStatistic
  PostalAddress location
  string location
  Place location
  VirtualLocation location
  string address
  PostalAddress address
  ProgramMembership memberOf
  Organization memberOf
  string publishingPrinciples
  CreativeWork publishingPrinciples
  string diversityStaffingReport
  Article diversityStaffingReport
  CreativeWork diversityPolicy
  string diversityPolicy
  string email
  Person employees
  NonprofitType nonprofitStatus
  string slogan
  string ethicsPolicy
  CreativeWork ethicsPolicy
  Organization brand
  Brand brand
  Organization sponsor
  Person sponsor
  string logo
  ImageObject logo
  string actionableFeedbackPolicy
  CreativeWork actionableFeedbackPolicy
  string naics
  ContactPoint contactPoint
  GeoShape serviceArea
  AdministrativeArea serviceArea
  Place serviceArea
  string isicV4
  MerchantReturnPolicy hasMerchantReturnPolicy
  Place hasPOS
  Person founder
  CreativeWork unnamedSourcesPolicy
  string unnamedSourcesPolicy
  Place foundingLocation
  string duns
  Organization parentOrganization
  Person alumni
  string leiCode
  AdministrativeArea areaServed
  GeoShape areaServed
  string areaServed
  Place areaServed
  date foundingDate
  Language knowsLanguage
  string knowsLanguage
  Review reviews
  Demand seeks
  string taxID
  Product owns
  OwnershipInfo owns
  OfferCatalog hasOfferCatalog
  Person members
  Organization members
  Event events
  string iso6523Code
  Organization department
  string faxNumber
  Event event

 }
