classDiagram
  OwnershipInfo -- dateTime
  OwnershipInfo -- Product
  OwnershipInfo -- Service
  OwnershipInfo -- Organization
  OwnershipInfo -- Person


class OwnershipInfo {

  dateTime ownedFrom
  Product typeOfGood
  Service typeOfGood
  Organization acquiredFrom
  Person acquiredFrom
  dateTime ownedThrough

 }
