classDiagram
  PayAction -- Person
  PayAction -- Audience
  PayAction -- ContactPoint
  PayAction -- Organization


class PayAction {

  Person recipient
  Audience recipient
  ContactPoint recipient
  Organization recipient

 }
