classDiagram
  PaymentCard -- MonetaryAmount


class PaymentCard {

  number cashBack
  boolean cashBack
  MonetaryAmount monthlyMinimumRepaymentAmount
  number monthlyMinimumRepaymentAmount
  MonetaryAmount floorLimit
  boolean contactlessPayment

 }
