classDiagram
  Physician -- MedicalTest
  Physician -- MedicalProcedure
  Physician -- MedicalTherapy
  Physician -- MedicalSpecialty
  Physician -- Hospital


class Physician {

  MedicalTest availableService
  MedicalProcedure availableService
  MedicalTherapy availableService
  MedicalSpecialty medicalSpecialty
  Hospital hospitalAffiliation

 }
