classDiagram
  PhysicalActivity -- PhysicalActivityCategory
  PhysicalActivity -- Thing
  PhysicalActivity -- CategoryCode
  PhysicalActivity -- AnatomicalStructure
  PhysicalActivity -- AnatomicalSystem
  PhysicalActivity -- SuperficialAnatomy


class PhysicalActivity {

  string category
  string category
  PhysicalActivityCategory category
  Thing category
  CategoryCode category
  string pathophysiology
  AnatomicalStructure associatedAnatomy
  AnatomicalSystem associatedAnatomy
  SuperficialAnatomy associatedAnatomy
  string epidemiology

 }
