classDiagram
  Place -- Review
  Place -- Place
  Place -- GeospatialGeometry
  Place -- DefinedTerm
  Place -- AggregateRating
  Place -- PostalAddress
  Place -- LocationFeatureSpecification
  Place -- ImageObject
  Place -- Photograph
  Place -- PropertyValue
  Place -- OpeningHoursSpecification
  Place -- Map
  Place -- GeoCoordinates
  Place -- GeoShape
  Place -- Event


class Place {

  string telephone
  Review review
  string maps
  Place geoContains
  GeospatialGeometry geoContains
  number maximumAttendeeCapacity
  Place containsPlace
  boolean smokingAllowed
  string globalLocationNumber
  DefinedTerm keywords
  string keywords
  string keywords
  GeospatialGeometry geoIntersects
  Place geoIntersects
  string latitude
  number latitude
  Place geoTouches
  GeospatialGeometry geoTouches
  Place geoCoveredBy
  GeospatialGeometry geoCoveredBy
  AggregateRating aggregateRating
  string address
  PostalAddress address
  Place geoEquals
  GeospatialGeometry geoEquals
  string map
  boolean publicAccess
  GeospatialGeometry geoCrosses
  Place geoCrosses
  Place containedInPlace
  LocationFeatureSpecification amenityFeature
  string slogan
  ImageObject photos
  Photograph photos
  GeospatialGeometry geoCovers
  Place geoCovers
  Place containedIn
  boolean hasDriveThroughService
  string logo
  ImageObject logo
  boolean isAccessibleForFree
  Place geoWithin
  GeospatialGeometry geoWithin
  GeospatialGeometry geoDisjoint
  Place geoDisjoint
  string tourBookingPage
  string isicV4
  GeospatialGeometry geoOverlaps
  Place geoOverlaps
  string branchCode
  PropertyValue additionalProperty
  OpeningHoursSpecification openingHoursSpecification
  Review reviews
  Photograph photo
  ImageObject photo
  OpeningHoursSpecification specialOpeningHoursSpecification
  string hasMap
  Map hasMap
  number longitude
  string longitude
  GeoCoordinates geo
  GeoShape geo
  Event events
  string faxNumber
  Event event

 }
