classDiagram
  PriceSpecification -- QuantitativeValue
  PriceSpecification -- dateTime
  PriceSpecification -- date
  PriceSpecification -- PriceSpecification


class PriceSpecification {

  number minPrice
  QuantitativeValue eligibleQuantity
  dateTime validFrom
  date validFrom
  number maxPrice
  string priceCurrency
  boolean valueAddedTaxIncluded
  PriceSpecification eligibleTransactionVolume
  dateTime validThrough
  date validThrough
  number price
  string price

 }
