classDiagram
  ProductModel -- ProductModel
  ProductModel -- ProductGroup


class ProductModel {

  ProductModel successorOf
  ProductModel predecessorOf
  ProductModel isVariantOf
  ProductGroup isVariantOf

 }
