classDiagram
  Property -- Class
  Property -- Enumeration
  Property -- Property


class Property {

  Class domainIncludes
  Enumeration supersededBy
  Class supersededBy
  Property supersededBy
  Class rangeIncludes
  Property inverseOf

 }
