classDiagram
  Rating -- Person
  Rating -- Organization


class Rating {

  string reviewAspect
  string worstRating
  number worstRating
  Person author
  Organization author
  string bestRating
  number bestRating
  number ratingValue
  string ratingValue
  string ratingExplanation

 }
