classDiagram
  RentalCarReservation -- Place
  RentalCarReservation -- dateTime


class RentalCarReservation {

  Place dropoffLocation
  dateTime dropoffTime
  dateTime pickupTime
  Place pickupLocation

 }
