classDiagram
  RepaymentSpecification -- MonetaryAmount


class RepaymentSpecification {

  number numberOfLoanPayments
  MonetaryAmount earlyPrepaymentPenalty
  MonetaryAmount loanPaymentAmount
  number loanPaymentFrequency
  number downPayment
  MonetaryAmount downPayment

 }
