classDiagram
  RiskChain -- ChainCompositionOr, ChainOperator, Situation
  RiskChain -- RiskObject
  RiskChain -- Relation


class RiskChain {

  ChainCompositionOr, ChainOperator, Situation[] chain
  RiskObject[] actors
  Relation[] relations

 }
