classDiagram
  Role -- dateTime
  Role -- date


class Role {

  string namedPosition
  string namedPosition
  dateTime startDate
  date startDate
  date endDate
  dateTime endDate
  string roleName
  string roleName

 }
