classDiagram
  ShippingRateSettings -- DefinedRegion
  ShippingRateSettings -- MonetaryAmount
  ShippingRateSettings -- DeliveryChargeSpecification


class ShippingRateSettings {

  DefinedRegion shippingDestination
  boolean doesNotShip
  string shippingLabel
  boolean isUnlabelledFallback
  MonetaryAmount shippingRate
  MonetaryAmount freeShippingThreshold
  DeliveryChargeSpecification freeShippingThreshold

 }
