classDiagram
  SizeSpecification -- SizeGroupEnumeration
  SizeSpecification -- QuantitativeValue
  SizeSpecification -- SizeSystemEnumeration
  SizeSpecification -- GenderType


class SizeSpecification {

  string sizeGroup
  SizeGroupEnumeration sizeGroup
  QuantitativeValue suggestedMeasurement
  QuantitativeValue suggestedAge
  QuantitativeValue hasMeasurement
  string sizeSystem
  SizeSystemEnumeration sizeSystem
  GenderType suggestedGender
  string suggestedGender

 }
