classDiagram
  SoftwareSourceCode -- ComputerLanguage
  SoftwareSourceCode -- SoftwareApplication


class SoftwareSourceCode {

  string programmingLanguage
  ComputerLanguage programmingLanguage
  string sampleType
  string runtimePlatform
  string runtime
  SoftwareApplication targetProduct
  string codeRepository
  string codeSampleType

 }
