classDiagram
  Suite -- QuantitativeValue
  Suite -- BedDetails
  Suite -- BedType


class Suite {

  QuantitativeValue numberOfRooms
  number numberOfRooms
  BedDetails bed
  string bed
  BedType bed
  QuantitativeValue occupancy

 }
