classDiagram
  TaxiReservation -- QuantitativeValue
  TaxiReservation -- dateTime
  TaxiReservation -- Place


class TaxiReservation {

  number partySize
  QuantitativeValue partySize
  dateTime pickupTime
  Place pickupLocation

 }
