classDiagram
  TipAction -- Person
  TipAction -- Audience
  TipAction -- ContactPoint
  TipAction -- Organization


class TipAction {

  Person recipient
  Audience recipient
  ContactPoint recipient
  Organization recipient

 }
