classDiagram
  Trip -- time
  Trip -- dateTime
  Trip -- Offer
  Trip -- Demand
  Trip -- Organization
  Trip -- Person
  Trip -- Trip
  Trip -- ItemList
  Trip -- Place


class Trip {

  time arrivalTime
  dateTime arrivalTime
  Offer offers
  Demand offers
  time departureTime
  dateTime departureTime
  Organization provider
  Person provider
  Trip subTrip
  ItemList itinerary
  Place itinerary
  Trip partOfTrip

 }
