classDiagram
  UKNonprofitType -- UKNonprofitType


class UKNonprofitType {

  UKNonprofitType UnincorporatedAssociationCharity
  UKNonprofitType UKTrust
  UKNonprofitType CharitableIncorporatedOrganization
  UKNonprofitType LimitedByGuaranteeCharity

 }
