classDiagram
  UserComments -- CreativeWork
  UserComments -- dateTime
  UserComments -- date
  UserComments -- Organization
  UserComments -- Person


class UserComments {

  string replyToUrl
  CreativeWork discusses
  dateTime commentTime
  date commentTime
  string commentText
  Organization creator
  Person creator

 }
