classDiagram
  VisualArtwork -- QuantitativeValue
  VisualArtwork -- Distance
  VisualArtwork -- Person


class VisualArtwork {

  QuantitativeValue width
  Distance width
  Person letterer
  Distance height
  QuantitativeValue height
  string surface
  string surface
  Person colorist
  Person inker
  string artform
  string artform
  string artworkSurface
  string artworkSurface
  number artEdition
  string artEdition
  Distance depth
  QuantitativeValue depth
  Person penciler
  Person artist
  string artMedium
  string artMedium

 }
