classDiagram
  class WearableMeasurementTypeEnumeration {
<<enumeration>>
  o WearableMeasurementSleeve
  o WearableMeasurementChestOrBust
  o WearableMeasurementOutsideLeg
  o WearableMeasurementCup
  o . . . 8 more values
 }
