classDiagram
  WebPage -- date
  WebPage -- Specialty
  WebPage -- ImageObject
  WebPage -- Organization
  WebPage -- Person
  WebPage -- WebPageElement
  WebPage -- SpeakableSpecification
  WebPage -- BreadcrumbList


class WebPage {

  date lastReviewed
  Specialty specialty
  ImageObject primaryImageOfPage
  string significantLink
  Organization reviewedBy
  Person reviewedBy
  WebPageElement mainContentOfPage
  string relatedLink
  string speakable
  SpeakableSpecification speakable
  BreadcrumbList breadcrumb
  string breadcrumb
  string significantLinks

 }
