MobileApplication:
  type: object
  documentation:
    en: A software application designed specifically to work well on a mobile device
      such as a telephone.
  inherit: SoftwareApplication
  properties:
    carrierRequirements:
      type: string
      documentation:
        en: Specifies specific carrier(s) requirements for the application (e.g. an
          application may only work on a specific carrier network).
