Recipe:
  type: object
  documentation:
    en: A recipe. For dietary restrictions covered by the recipe, a few common
      restrictions are enumerated via [[suitableForDiet]]. The [[keywords]]
      property can also be used to add more detail.
  inherit: HowTo
  properties:
    recipeInstructions:
      type:
        - string
        - CreativeWork
        - ItemList
      documentation:
        en: A step in making the recipe, in the form of a single item (document, video,
          etc.) or an ordered list with HowToStep and/or HowToSection items.
    ingredients:
      type: string
      documentation:
        en: A single ingredient used in the recipe, e.g. sugar, flour or garlic.
    recipeCuisine:
      type: string
      documentation:
        en: The cuisine of the recipe (for example, French or Ethiopian).
    suitableForDiet:
      type: RestrictedDiet
      documentation:
        en: Indicates a dietary restriction or guideline for which this recipe or menu
          item is suitable, e.g. diabetic, halal etc.
    nutrition:
      type: NutritionInformation
      documentation:
        en: Nutrition information about the recipe or menu item.
    cookingMethod:
      type: string
      documentation:
        en: The method of cooking, such as Frying, Steaming, ...
    recipeIngredient:
      type: string
      documentation:
        en: A single ingredient used in the recipe, e.g. sugar, flour or garlic.
    recipeYield:
      type:
        - string
        - QuantitativeValue
      documentation:
        en: The quantity produced by the recipe (for example, number of people served,
          number of servings, etc).
    cookTime:
      type: Duration
      documentation:
        en: The time it takes to actually cook the dish, in [ISO 8601 duration
          format](http://en.wikipedia.org/wiki/ISO_8601).
    recipeCategory:
      type: string
      documentation:
        en: The category of the recipe—for example, appetizer, entree, etc.
