Service:
  type: object
  documentation:
    en: A service provided by an organization, e.g. delivery service, print
      services, etc.
  inherit: Intangible
  properties:
    review:
      type: Review
      documentation:
        en: A review of the item.
    award:
      type: string
      documentation:
        en: An award won by or for this item.
    serviceAudience:
      type: Audience
      documentation:
        en: The audience eligible for this service.
    category:
      type:
        - string
        - string
        - PhysicalActivityCategory
        - Thing
        - CategoryCode
      documentation:
        en: A category for the item. Greater signs or slashes can be used to informally
          indicate a category hierarchy.
    hoursAvailable:
      type: OpeningHoursSpecification
      documentation:
        en: The hours during which this service or contact is available.
    audience:
      type: Audience
      documentation:
        en: An intended audience, i.e. a group for whom something was created.
    offers:
      type:
        - Offer
        - Demand
      documentation:
        en: "An offer to provide this item&#x2014;for example, an offer to sell a
          product, rent the DVD of a movie, perform a service, or give away
          tickets to an event. Use [[businessFunction]] to indicate the kind of
          transaction offered, i.e. sell, lease, etc. This property can also be
          used to describe a [[Demand]]. While this property is listed as
          expected on a number of common types, it can be used in others. In
          that case, using a second type, such as Product or a subtype of
          Product, can clarify the nature of the offer.

          \      "
    serviceOutput:
      type: Thing
      documentation:
        en: The tangible thing generated by the service, e.g. a passport, permit, etc.
    provider:
      type:
        - Organization
        - Person
      documentation:
        en: The service provider, service operator, or service performer; the goods
          producer. Another party (a seller) may offer those services or goods
          on behalf of the provider. A provider may also serve as the seller.
    termsOfService:
      type:
        - string
        - string
      documentation:
        en: Human-readable terms of service documentation.
    providerMobility:
      type: string
      documentation:
        en: Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
    broker:
      type:
        - Person
        - Organization
      documentation:
        en: An entity that arranges for an exchange between a buyer and a seller.  In
          most cases a broker never acquires or releases ownership of a product
          or service involved in an exchange.  If it is not clear whether an
          entity is a broker, seller, or buyer, the latter two terms are
          preferred.
    aggregateRating:
      type: AggregateRating
      documentation:
        en: The overall rating, based on a collection of reviews or ratings, of the
          item.
    isSimilarTo:
      type:
        - Service
        - Product
      documentation:
        en: A pointer to another, functionally similar product (or multiple products).
    availableChannel:
      type: ServiceChannel
      documentation:
        en: A means of accessing the service (e.g. a phone bank, a web site, a location,
          etc.).
    slogan:
      type: string
      documentation:
        en: A slogan or motto associated with the item.
    brand:
      type:
        - Organization
        - Brand
      documentation:
        en: The brand(s) associated with a product or service, or the brand(s)
          maintained by an organization or business person.
    logo:
      type:
        - string
        - ImageObject
      documentation:
        en: An associated logo.
    produces:
      type: Thing
      documentation:
        en: The tangible thing generated by the service, e.g. a passport, permit, etc.
    serviceArea:
      type:
        - GeoShape
        - AdministrativeArea
        - Place
      documentation:
        en: The geographic area where the service is provided.
    serviceType:
      type:
        - GovernmentBenefitsType
        - string
      documentation:
        en: The type of service being offered, e.g. veterans' benefits, emergency
          relief, etc.
    areaServed:
      type:
        - AdministrativeArea
        - GeoShape
        - string
        - Place
      documentation:
        en: The geographic area where a service or offered item is provided.
    isRelatedTo:
      type:
        - Service
        - Product
      documentation:
        en: A pointer to another, somehow related product (or multiple products).
    hasOfferCatalog:
      type: OfferCatalog
      documentation:
        en: Indicates an OfferCatalog listing for this Organization, Person, or Service.
