SoftwareApplication:
  type: object
  documentation:
    en: A software application.
  inherit: CreativeWork
  properties:
    countriesSupported:
      type: string
      documentation:
        en: Countries for which the application is supported. You can also provide the
          two-letter ISO 3166-1 alpha-2 country code.
    installUrl:
      type: string
      documentation:
        en: URL at which the app may be installed, if different from the URL of the
          item.
    operatingSystem:
      type: string
      documentation:
        en: Operating systems supported (Windows 7, OSX 10.6, Android 1.6).
    memoryRequirements:
      type:
        - string
        - string
      documentation:
        en: Minimum memory requirements.
    softwareVersion:
      type: string
      documentation:
        en: Version of the software instance.
    storageRequirements:
      type:
        - string
        - string
      documentation:
        en: Storage requirements (free space required).
    softwareHelp:
      type: CreativeWork
      documentation:
        en: Software application help.
    applicationSubCategory:
      type:
        - string
        - string
      documentation:
        en: Subcategory of the application, e.g. 'Arcade Game'.
    downloadUrl:
      type: string
      documentation:
        en: If the file can be downloaded, URL to download the binary.
    applicationCategory:
      type:
        - string
        - string
      documentation:
        en: Type of software application, e.g. 'Game, Multimedia'.
    countriesNotSupported:
      type: string
      documentation:
        en: Countries for which the application is not supported. You can also provide
          the two-letter ISO 3166-1 alpha-2 country code.
    softwareRequirements:
      type:
        - string
        - string
      documentation:
        en: "Component dependency requirements for application. This includes runtime
          environments and shared libraries that are not included in the
          application distribution package, but required to run the application
          (Examples: DirectX, Java or .NET runtime)."
    softwareAddOn:
      type: SoftwareApplication
      documentation:
        en: Additional content for a software application.
    applicationSuite:
      type: string
      documentation:
        en: The name of the application suite to which the application belongs (e.g.
          Excel belongs to Office).
    requirements:
      type:
        - string
        - string
      documentation:
        en: "Component dependency requirements for application. This includes runtime
          environments and shared libraries that are not included in the
          application distribution package, but required to run the application
          (Examples: DirectX, Java or .NET runtime)."
    permissions:
      type: string
      documentation:
        en: Permission(s) required to run the app (for example, a mobile app may require
          full internet access or may run only on wifi).
    processorRequirements:
      type: string
      documentation:
        en: Processor architecture required to run the application (e.g. IA64).
    screenshot:
      type:
        - ImageObject
        - string
      documentation:
        en: A link to a screenshot image of the app.
    featureList:
      type:
        - string
        - string
      documentation:
        en: Features or modules provided by this application (and possibly required by
          other applications).
    releaseNotes:
      type:
        - string
        - string
      documentation:
        en: Description of what changed in this version.
    supportingData:
      type: DataFeed
      documentation:
        en: Supporting data for a SoftwareApplication.
    fileSize:
      type: string
      documentation:
        en: Size of the application / package (e.g. 18MB). In the absence of a unit (MB,
          KB etc.), KB will be assumed.
    device:
      type: string
      documentation:
        en: Device required to run the application. Used in cases where a specific
          make/model is required to run the application.
    availableOnDevice:
      type: string
      documentation:
        en: Device required to run the application. Used in cases where a specific
          make/model is required to run the application.
