TrainReservation:
  type: object
  documentation:
    en: "A reservation for train travel.\\n\\nNote: This type is for information
      about actual reservations, e.g. in confirmation emails or HTML pages with
      individual confirmations of reservations. For offers of tickets, use
      [[Offer]]."
  inherit: Reservation
  properties: {}
