WebApplication:
  type: object
  documentation:
    en: Web applications.
  inherit: SoftwareApplication
  properties:
    browserRequirements:
      type: string
      documentation:
        en: Specifies browser requirements in human-readable text. For example,
          'requires HTML5 support'.
