classDiagram
  Accommodation -- QuantitativeValue
  Accommodation -- Duration
  Accommodation -- LocationFeatureSpecification
  Accommodation -- FloorPlan


class Accommodation {

  string floorLevel
  number numberOfBathroomsTotal
  QuantitativeValue numberOfRooms
  number numberOfRooms
  QuantitativeValue leaseLength
  Duration leaseLength
  number yearBuilt
  string accommodationCategory
  LocationFeatureSpecification amenityFeature
  string tourBookingPage
  number numberOfBedrooms
  QuantitativeValue numberOfBedrooms
  number numberOfPartialBathrooms
  QuantitativeValue floorSize
  FloorPlan accommodationFloorPlan
  number numberOfFullBathrooms
  string permittedUsage
  string petsAllowed
  boolean petsAllowed

 }
