classDiagram
  ActionAccessSpecification -- Offer
ActionAccessSpecification -- string,string,PhysicalActivityCategory,Thing,CategoryCode
ActionAccessSpecification -- Place,string,GeoShape
ActionAccessSpecification -- MediaSubscription,boolean
ActionAccessSpecification -- date,dateTime,time
ActionAccessSpecification -- GeoShape,string,Place
ActionAccessSpecification -- time,dateTime,date


Intangible <|-- ActionAccessSpecification
class ActionAccessSpecification {

  Offer expectsAcceptanceOf
  string,string,PhysicalActivityCategory,Thing,CategoryCode category
  Place,string,GeoShape ineligibleRegion
  MediaSubscription,boolean requiresSubscription
  date,dateTime,time availabilityEnds
  GeoShape,string,Place eligibleRegion
  time,dateTime,date availabilityStarts

}
