classDiagram
  Action -- Organization
  Action -- Person
  Action -- dateTime
  Action -- time
  Action -- ActionStatusType
  Action -- Thing
  Action -- PostalAddress
  Action -- Place
  Action -- VirtualLocation
  Action -- EntryPoint


class Action {

  Organization agent
  Person agent
  dateTime startTime
  time startTime
  ActionStatusType actionStatus
  Organization provider
  Person provider
  Thing result
  PostalAddress location
  string location
  Place location
  VirtualLocation location
  Thing object
  EntryPoint target
  dateTime endTime
  time endTime
  Organization participant
  Person participant
  Thing instrument
  Thing error

 }
