classDiagram
  Action -- Organization,Person
Action -- dateTime,time
Action -- ActionStatusType
Action -- Thing
Action -- PostalAddress,string,Place,VirtualLocation
Action -- EntryPoint


Thing <|-- Action
class Action {

  Organization,Person agent
  dateTime,time startTime
  ActionStatusType actionStatus
  Organization,Person provider
  Thing result
  PostalAddress,string,Place,VirtualLocation location
  Thing object
  EntryPoint target
  dateTime,time endTime
  Organization,Person participant
  Thing instrument
  Thing error

}
