classDiagram
Enumeration o-- AdultOrientedEnumeration
  class AdultOrientedEnumeration {
<<enumeration>>
  o ReducedRelevanceForChildrenConsideration
  o SexualContentConsideration
  o UnclassifiedAdultConsideration
  o HealthcareConsideration
  o . . . 6 more values
}
