classDiagram
  Amount -- Operation, Variable, number
  Amount -- UnitDistanceEnum, UnitMassEnum, UnitMonetaryEnum, UnitPersonEnum, UnitTimeEnum, string
  Amount -- UnitDimensionEnum


class Amount {

  Operation, Variable, number quantity
  UnitDistanceEnum, UnitMassEnum, UnitMonetaryEnum, UnitPersonEnum, UnitTimeEnum, string unit
  UnitDimensionEnum unitDimension

 }
