classDiagram
  ApartmentComplex -- QuantitativeValue


class ApartmentComplex {

  QuantitativeValue numberOfAccommodationUnits
  QuantitativeValue numberOfAvailableAccommodationUnits
  string tourBookingPage
  number numberOfBedrooms
  QuantitativeValue numberOfBedrooms
  string petsAllowed
  boolean petsAllowed

 }
