classDiagram
  Article -- CreativeWork
  Article -- SpeakableSpecification


class Article {

  string pageStart
  number pageStart
  string articleSection
  string pageEnd
  number pageEnd
  string backstory
  CreativeWork backstory
  number wordCount
  string articleBody
  string speakable
  SpeakableSpecification speakable
  string pagination

 }
