classDiagram
  BankAccount -- string,string
BankAccount -- MonetaryAmount


FinancialProduct <|-- BankAccount
class BankAccount {

  string,string bankAccountType
  MonetaryAmount accountMinimumInflow
  MonetaryAmount accountOverdraftLimit

}
