classDiagram
MeasurementTypeEnumeration o-- BodyMeasurementTypeEnumeration
  class BodyMeasurementTypeEnumeration {
<<enumeration>>
  o BodyMeasurementHand
  o BodyMeasurementHips
  o BodyMeasurementUnderbust
  o BodyMeasurementWeight
  o . . . 9 more values
}
