classDiagram
  Brand -- Review
  Brand -- AggregateRating
  Brand -- ImageObject


class Brand {

  Review review
  AggregateRating aggregateRating
  string slogan
  string logo
  ImageObject logo

 }
