classDiagram
  Brand -- Review
Brand -- AggregateRating
Brand -- string,ImageObject


Intangible <|-- Brand
class Brand {

  Review review
  AggregateRating aggregateRating
  string slogan
  string,ImageObject logo

}
