classDiagram
  BroadcastFrequencySpecification -- QualitativeValue
  BroadcastFrequencySpecification -- QuantitativeValue


class BroadcastFrequencySpecification {

  string broadcastSubChannel
  QualitativeValue broadcastSignalModulation
  string broadcastSignalModulation
  number broadcastFrequencyValue
  QuantitativeValue broadcastFrequencyValue

 }
