classDiagram
  BroadcastService -- BroadcastService
BroadcastService -- BroadcastFrequencySpecification,string
BroadcastService -- string,Language
BroadcastService -- BroadcastChannel
BroadcastService -- Organization
BroadcastService -- Place


Service <|-- BroadcastService
class BroadcastService {

  BroadcastService parentService
  string broadcastDisplayName
  string videoFormat
  string broadcastTimezone
  BroadcastFrequencySpecification,string broadcastFrequency
  string callSign
  string,Language inLanguage
  BroadcastChannel hasBroadcastChannel
  Organization broadcaster
  Organization broadcastAffiliateOf
  Place area

}
