classDiagram
  BroadcastEvent -- Language
  BroadcastEvent -- Event


class BroadcastEvent {

  Language subtitleLanguage
  string subtitleLanguage
  string videoFormat
  Event broadcastOfEvent
  boolean isLiveBroadcast

 }
