classDiagram
  BusinessAudience -- QuantitativeValue


Audience <|-- BusinessAudience
class BusinessAudience {

  QuantitativeValue yearlyRevenue
  QuantitativeValue numberOfEmployees
  QuantitativeValue yearsInOperation

}
