classDiagram
  BuyAction -- WarrantyPromise
BuyAction -- Organization,Person
BuyAction -- Person,Organization


TradeAction <|-- BuyAction
class BuyAction {

  WarrantyPromise warrantyPromise
  Organization,Person seller
  Person,Organization vendor

}
