classDiagram
  BuyAction -- WarrantyPromise
  BuyAction -- Organization
  BuyAction -- Person


class BuyAction {

  WarrantyPromise warrantyPromise
  Organization seller
  Person seller
  Person vendor
  Organization vendor

 }
