classDiagram
  CDCPMDRecord -- dateTime
  CDCPMDRecord -- date


class CDCPMDRecord {

  number cvdNumBedsOcc
  number cvdNumICUBedsOcc
  number cvdNumVent
  number cvdNumC19Died
  number cvdNumTotBeds
  string cvdFacilityCounty
  number cvdNumICUBeds
  dateTime cvdCollectionDate
  string cvdCollectionDate
  number cvdNumC19HOPats
  number cvdNumC19OFMechVentPats
  string cvdFacilityId
  number cvdNumVentUse
  number cvdNumBeds
  number cvdNumC19MechVentPats
  date datePosted
  dateTime datePosted
  number cvdNumC19OverflowPats
  number cvdNumC19HospPats

 }
