classDiagram
  Claim -- Person
  Claim -- Organization
  Claim -- CreativeWork


class Claim {

  Person claimInterpreter
  Organization claimInterpreter
  CreativeWork firstAppearance
  CreativeWork appearance

 }
