classDiagram
  CompoundPriceSpecification -- UnitPriceSpecification
  CompoundPriceSpecification -- PriceTypeEnumeration


class CompoundPriceSpecification {

  UnitPriceSpecification priceComponent
  PriceTypeEnumeration priceType
  string priceType

 }
