classDiagram
  CompoundPriceSpecification -- UnitPriceSpecification
CompoundPriceSpecification -- PriceTypeEnumeration,string


PriceSpecification <|-- CompoundPriceSpecification
class CompoundPriceSpecification {

  UnitPriceSpecification priceComponent
  PriceTypeEnumeration,string priceType

}
