classDiagram
  ConsumeAction -- Offer
ConsumeAction -- ActionAccessSpecification


Action <|-- ConsumeAction
class ConsumeAction {

  Offer expectsAcceptanceOf
  ActionAccessSpecification actionAccessibilityRequirement

}
