classDiagram
  CreativeWork -- DefinedTerm
  CreativeWork -- date
  CreativeWork -- dateTime
  CreativeWork -- Product
  CreativeWork -- Review
  CreativeWork -- Person
  CreativeWork -- Organization
  CreativeWork -- Country
  CreativeWork -- Grant
  CreativeWork -- Audience
  CreativeWork -- Offer
  CreativeWork -- Demand
  CreativeWork -- Place
  CreativeWork -- MediaObject
  CreativeWork -- QuantitativeValue
  CreativeWork -- Thing
  CreativeWork -- CreativeWork
  CreativeWork -- Comment
  CreativeWork -- PublicationEvent
  CreativeWork -- AggregateRating
  CreativeWork -- Duration
  CreativeWork -- InteractionCounter
  CreativeWork -- Event
  CreativeWork -- AlignmentObject
  CreativeWork -- CorrectionComment
  CreativeWork -- Rating
  CreativeWork -- SizeSpecification
  CreativeWork -- Language
  CreativeWork -- Claim
  CreativeWork -- WebPage
  CreativeWork -- AudioObject
  CreativeWork -- MusicRecording
  CreativeWork -- Clip
  CreativeWork -- ItemList
  CreativeWork -- VideoObject


class CreativeWork {

  DefinedTerm teaches
  string teaches
  string educationalLevel
  DefinedTerm educationalLevel
  string educationalLevel
  string abstract
  string creativeWorkStatus
  DefinedTerm creativeWorkStatus
  date expires
  dateTime contentReferenceTime
  string material
  string material
  Product material
  Review review
  string fileFormat
  string fileFormat
  string text
  Person translator
  Organization translator
  string award
  string assesses
  DefinedTerm assesses
  string copyrightNotice
  string schemaVersion
  string schemaVersion
  Country countryOfOrigin
  DefinedTerm pattern
  string pattern
  Person accountablePerson
  Grant funding
  DefinedTerm educationalUse
  string educationalUse
  string genre
  string genre
  DefinedTerm keywords
  string keywords
  string keywords
  number position
  string position
  string accessibilityHazard
  string alternativeHeadline
  Audience audience
  Offer offers
  Demand offers
  Place locationCreated
  MediaObject associatedMedia
  QuantitativeValue [object Object]
  string [object Object]
  Thing mainEntity
  Organization copyrightHolder
  Person copyrightHolder
  string awards
  Place contentLocation
  date sdDatePublished
  Organization producer
  Person producer
  Place spatial
  Person publisher
  Organization publisher
  Organization sourceOrganization
  Person character
  Organization funder
  Person funder
  CreativeWork exampleOfWork
  CreativeWork usageInfo
  string usageInfo
  Organization provider
  Person provider
  Organization sdPublisher
  Person sdPublisher
  Comment comment
  string accessibilityFeature
  PublicationEvent publication
  CreativeWork translationOfWork
  string interactivityType
  number commentCount
  string accessMode
  AggregateRating aggregateRating
  Duration timeRequired
  string typicalAgeRange
  InteractionCounter interactionStatistic
  number copyrightYear
  CreativeWork isBasedOn
  string isBasedOn
  Product isBasedOn
  CreativeWork workExample
  string publishingPrinciples
  CreativeWork publishingPrinciples
  string discussionUrl
  PublicationEvent releasedEvent
  date dateCreated
  dateTime dateCreated
  CreativeWork workTranslation
  Person editor
  string creditText
  Event recordedAt
  string editEIDR
  string editEIDR
  Person author
  Organization author
  dateTime dateModified
  date dateModified
  Organization sponsor
  Person sponsor
  string accessibilitySummary
  string encodingFormat
  string encodingFormat
  Person maintainer
  Organization maintainer
  AlignmentObject educationalAlignment
  CreativeWork acquireLicensePage
  string acquireLicensePage
  boolean isAccessibleForFree
  date datePublished
  dateTime datePublished
  Place spatialCoverage
  CreativeWork sdLicense
  string sdLicense
  string conditionsOfAccess
  string correction
  string correction
  CorrectionComment correction
  string contentRating
  Rating contentRating
  QuantitativeValue size
  DefinedTerm size
  string size
  SizeSpecification size
  string isPartOf
  CreativeWork isPartOf
  dateTime temporal
  string temporal
  string thumbnailUrl
  string inLanguage
  Language inLanguage
  string license
  CreativeWork license
  Organization creator
  Person creator
  Review reviews
  Thing about
  boolean isFamilyFriendly
  string headline
  string accessibilityAPI
  Organization publisherImprint
  string isBasedOnUrl
  CreativeWork isBasedOnUrl
  Product isBasedOnUrl
  MediaObject encodings
  Claim interpretedAsClaim
  string accessibilityControl
  CreativeWork citation
  string citation
  number version
  string version
  WebPage archivedAt
  string archivedAt
  DefinedTerm learningResourceType
  string learningResourceType
  MediaObject encoding
  AudioObject audio
  MusicRecording audio
  Clip audio
  Thing mentions
  ItemList accessModeSufficient
  CreativeWork hasPart
  string temporalCoverage
  dateTime temporalCoverage
  string temporalCoverage
  Organization contributor
  Person contributor
  Clip video
  VideoObject video

 }
