classDiagram
  CreativeWork -- DefinedTerm,string
CreativeWork -- string,DefinedTerm,string
CreativeWork -- string,DefinedTerm
CreativeWork -- date
CreativeWork -- dateTime
CreativeWork -- string,string,Product
CreativeWork -- Review
CreativeWork -- string,string
CreativeWork -- Person,Organization
CreativeWork -- Country
CreativeWork -- Person
CreativeWork -- Grant
CreativeWork -- DefinedTerm,string,string
CreativeWork -- number,string
CreativeWork -- Audience
CreativeWork -- Offer,Demand
CreativeWork -- Place
CreativeWork -- MediaObject
CreativeWork -- QuantitativeValue,string
CreativeWork -- Thing
CreativeWork -- Organization,Person
CreativeWork -- Organization
CreativeWork -- CreativeWork
CreativeWork -- CreativeWork,string
CreativeWork -- Comment
CreativeWork -- PublicationEvent
CreativeWork -- AggregateRating
CreativeWork -- Duration
CreativeWork -- InteractionCounter
CreativeWork -- CreativeWork,string,Product
CreativeWork -- string,CreativeWork
CreativeWork -- date,dateTime
CreativeWork -- Event
CreativeWork -- dateTime,date
CreativeWork -- AlignmentObject
CreativeWork -- string,string,CorrectionComment
CreativeWork -- string,Rating
CreativeWork -- QuantitativeValue,DefinedTerm,string,SizeSpecification
CreativeWork -- dateTime,string
CreativeWork -- string,Language
CreativeWork -- string,CreativeWork,Product
CreativeWork -- Claim
CreativeWork -- WebPage,string
CreativeWork -- AudioObject,MusicRecording,Clip
CreativeWork -- ItemList
CreativeWork -- string,dateTime,string
CreativeWork -- Clip,VideoObject


Thing <|-- CreativeWork
class CreativeWork {

  DefinedTerm,string teaches
  string,DefinedTerm,string educationalLevel
  string abstract
  string,DefinedTerm creativeWorkStatus
  date expires
  dateTime contentReferenceTime
  string,string,Product material
  Review review
  string,string fileFormat
  string text
  Person,Organization translator
  string award
  string,DefinedTerm assesses
  string copyrightNotice
  string,string schemaVersion
  Country countryOfOrigin
  DefinedTerm,string pattern
  Person accountablePerson
  Grant funding
  DefinedTerm,string educationalUse
  string,string genre
  DefinedTerm,string,string keywords
  number,string position
  string accessibilityHazard
  string alternativeHeadline
  Audience audience
  Offer,Demand offers
  Place locationCreated
  MediaObject associatedMedia
  QuantitativeValue,string [object Object]
  Thing mainEntity
  Organization,Person copyrightHolder
  string awards
  Place contentLocation
  date sdDatePublished
  Organization,Person producer
  Place spatial
  Person,Organization publisher
  Organization sourceOrganization
  Person character
  Organization,Person funder
  CreativeWork exampleOfWork
  CreativeWork,string usageInfo
  Organization,Person provider
  Organization,Person sdPublisher
  Comment comment
  string accessibilityFeature
  PublicationEvent publication
  CreativeWork translationOfWork
  string interactivityType
  number commentCount
  string accessMode
  AggregateRating aggregateRating
  Duration timeRequired
  string typicalAgeRange
  InteractionCounter interactionStatistic
  number copyrightYear
  CreativeWork,string,Product isBasedOn
  CreativeWork workExample
  string,CreativeWork publishingPrinciples
  string discussionUrl
  PublicationEvent releasedEvent
  date,dateTime dateCreated
  CreativeWork workTranslation
  Person editor
  string creditText
  Event recordedAt
  string,string editEIDR
  Person,Organization author
  dateTime,date dateModified
  Organization,Person sponsor
  string accessibilitySummary
  string,string encodingFormat
  Person,Organization maintainer
  AlignmentObject educationalAlignment
  CreativeWork,string acquireLicensePage
  boolean isAccessibleForFree
  date,dateTime datePublished
  Place spatialCoverage
  CreativeWork,string sdLicense
  string conditionsOfAccess
  string,string,CorrectionComment correction
  string,Rating contentRating
  QuantitativeValue,DefinedTerm,string,SizeSpecification size
  string,CreativeWork isPartOf
  dateTime,string temporal
  string thumbnailUrl
  string,Language inLanguage
  string,CreativeWork license
  Organization,Person creator
  Review reviews
  Thing about
  boolean isFamilyFriendly
  string headline
  string accessibilityAPI
  Organization publisherImprint
  string,CreativeWork,Product isBasedOnUrl
  MediaObject encodings
  Claim interpretedAsClaim
  string accessibilityControl
  CreativeWork,string citation
  number,string version
  WebPage,string archivedAt
  DefinedTerm,string learningResourceType
  MediaObject encoding
  AudioObject,MusicRecording,Clip audio
  Thing mentions
  ItemList accessModeSufficient
  CreativeWork hasPart
  string,dateTime,string temporalCoverage
  Organization,Person contributor
  Clip,VideoObject video

}
