classDiagram
  DataFeedItem -- dateTime,date
DataFeedItem -- date,dateTime
DataFeedItem -- Thing


Intangible <|-- DataFeedItem
class DataFeedItem {

  dateTime,date dateDeleted
  date,dateTime dateCreated
  dateTime,date dateModified
  Thing item

}
