classDiagram
  DatedMoneySpecification -- dateTime
  DatedMoneySpecification -- date
  DatedMoneySpecification -- MonetaryAmount


class DatedMoneySpecification {

  dateTime startDate
  date startDate
  date endDate
  dateTime endDate
  string currency
  number amount
  MonetaryAmount amount

 }
