classDiagram
  DDxElement -- MedicalSignOrSymptom
DDxElement -- MedicalCondition


MedicalIntangible <|-- DDxElement
class DDxElement {

  MedicalSignOrSymptom distinguishingSign
  MedicalCondition diagnosis

}
