classDiagram
  DefinedRegion -- Country,string
DefinedRegion -- PostalCodeRangeSpecification


StructuredValue <|-- DefinedRegion
class DefinedRegion {

  Country,string addressCountry
  string addressRegion
  PostalCodeRangeSpecification postalCodeRange
  string postalCodePrefix
  string postalCode

}
