classDiagram
  DeliveryTimeSettings -- DefinedRegion
  DeliveryTimeSettings -- ShippingDeliveryTime


class DeliveryTimeSettings {

  DefinedRegion shippingDestination
  string transitTimeLabel
  boolean isUnlabelledFallback
  ShippingDeliveryTime deliveryTime

 }
