classDiagram
  Demand -- Trip,Event,Product,AggregateOffer,CreativeWork,MenuItem,Service
Demand -- TypeAndQuantityNode
Demand -- BusinessFunction
Demand -- OfferItemCondition
Demand -- QuantitativeValue
Demand -- LoanOrCredit,PaymentMethod
Demand -- WarrantyPromise
Demand -- Organization,Person
Demand -- Place,string,GeoShape
Demand -- DeliveryMethod
Demand -- dateTime,date
Demand -- date,dateTime,time
Demand -- GeoShape,string,Place
Demand -- PriceSpecification
Demand -- AdministrativeArea,GeoShape,string,Place
Demand -- BusinessEntityType
Demand -- ItemAvailability
Demand -- time,dateTime,date
Demand -- Place


Intangible <|-- Demand
class Demand {

  string gtin12
  Trip,Event,Product,AggregateOffer,CreativeWork,MenuItem,Service itemOffered
  string mpn
  TypeAndQuantityNode includesObject
  BusinessFunction businessFunction
  OfferItemCondition itemCondition
  string gtin
  QuantitativeValue eligibleQuantity
  LoanOrCredit,PaymentMethod acceptedPaymentMethod
  WarrantyPromise warranty
  Organization,Person seller
  Place,string,GeoShape ineligibleRegion
  QuantitativeValue deliveryLeadTime
  DeliveryMethod availableDeliveryMethod
  dateTime,date validFrom
  date,dateTime,time availabilityEnds
  GeoShape,string,Place eligibleRegion
  string gtin8
  QuantitativeValue inventoryLevel
  string sku
  QuantitativeValue advanceBookingRequirement
  string gtin14
  PriceSpecification eligibleTransactionVolume
  AdministrativeArea,GeoShape,string,Place areaServed
  BusinessEntityType eligibleCustomerType
  ItemAvailability availability
  string gtin13
  dateTime,date validThrough
  PriceSpecification priceSpecification
  time,dateTime,date availabilityStarts
  QuantitativeValue eligibleDuration
  Place availableAtOrFrom
  string serialNumber

}
