classDiagram
Amount -- UnitEnum
Amount -- UnitDimensionEnum


class Amount {

  string quantity
  UnitEnum unit
  UnitDimensionEnum unitDimension

}

ChainCompositionOr -- RiskChain


Chainable <|-- ChainCompositionOr
class ChainCompositionOr {

  RiskChain[] operands

}

ChainOperator -- ChainOperatorEnum


Chainable <|-- ChainOperator
class ChainOperator {

  ChainOperatorEnum type

}

class ChainOperatorEnum {
<<enumeration>>
  o wildcard
  o not
}



class Chainable {
<<abstract>>


}

InsurancePayout -- PayoutTypeEnum
InsurancePayout -- Amount
InsurancePayout -- Multiplier
InsurancePayout -- RiskChain


class InsurancePayout {

  PayoutTypeEnum payoutType
  Amount[] amount
  Amount[] minimalAmount
  Multiplier multipliers
  RiskChain for
  boolean impactOtherConsumption

}

Multiplier -- MultiplierTimeEnum
Multiplier -- MultiplierPersonEnum
Multiplier -- MultiplierOccurrenceEnum
Multiplier -- MultiplierInsuredObjectEnum


class Multiplier {

  MultiplierTimeEnum time
  MultiplierPersonEnum person
  MultiplierOccurrenceEnum occurrence
  MultiplierInsuredObjectEnum insuredObject
  string[] other

}

class MultiplierInsuredObjectEnum {
<<enumeration>>
  o perCar
}

class MultiplierOccurrenceEnum {
<<enumeration>>
  o perClaim
  o perLine
  o perIncident
}

class MultiplierPersonEnum {
<<enumeration>>
  o perPerson
  o perPassenger
  o perEmployee
  o perLoneTraveler
}

class MultiplierTimeEnum {
<<enumeration>>
  o perMinutes
  o perHour
  o perDay
  o perMonth
  o . . . 3 more values
}

class PayoutTypeEnum {
<<enumeration>>
  o Limit
  o Excess
  o Deductible
  o Franchise
  o . . . 2 more values
}



class Relation {

  string impacterId
  string impactedId
  string verb

}

RiskChain -- Chainable
RiskChain -- RiskObject
RiskChain -- Relation


class RiskChain {

  Chainable[] chain
  RiskObject[] actors
  Relation[] relations

}



class RiskObject {
<<abstract>>

  string id

}



Chainable <|-- Situation
class Situation {

  string id
  string event
  string location
  string period

}

class UnitDimensionEnum {
<<enumeration>>
  o Monetary
  o Time
  o Distance
  o Person
}

UnitEnum o-- UnitDistanceEnum
  class UnitDistanceEnum {
<<enumeration>>
  o kilometer
  o miles
}

class UnitEnum {
<<enumeration>>
}

UnitEnum o-- UnitMonetaryEnum
  class UnitMonetaryEnum {
<<enumeration>>
  o AED
  o AFN
  o ALL
  o AMD
  o . . . 177 more values
}

UnitEnum o-- UnitPersonEnum
  class UnitPersonEnum {
<<enumeration>>
  o person
  o passenger
  o driver
  o policyholder
}

UnitEnum o-- UnitTimeEnum
  class UnitTimeEnum {
<<enumeration>>
  o day
  o consecutiveDay
  o night
  o month
  o . . . 1 more values
}

undefined
undefined
undefined
Person -- PersonRelationToPolicyHolderEnum


RiskObject <|-- Person
class Person {

  PersonRelationToPolicyHolderEnum relationToPolicyHolder
  string firstName
  string lastName
  number age

}

class PersonRelationToPolicyHolderEnum {
<<enumeration>>
  o self
  o father
  o mother
}
