classDiagram
  DonateAction -- Person
  DonateAction -- Audience
  DonateAction -- ContactPoint
  DonateAction -- Organization


class DonateAction {

  Person recipient
  Audience recipient
  ContactPoint recipient
  Organization recipient

 }
