classDiagram
  DriveWheelConfigurationValue -- schema:DriveWheelConfigurationValue


class DriveWheelConfigurationValue {

  schema:DriveWheelConfigurationValue FrontWheelDriveConfiguration
  schema:DriveWheelConfigurationValue FourWheelDriveConfiguration
  schema:DriveWheelConfigurationValue AllWheelDriveConfiguration
  schema:DriveWheelConfigurationValue RearWheelDriveConfiguration

 }
