classDiagram
  Drug -- DrugPregnancyCategory
  Drug -- DrugLegalStatus
  Drug -- MedicalEnumeration
  Drug -- Drug
  Drug -- MaximumDoseSchedule
  Drug -- DrugPrescriptionStatus
  Drug -- DrugClass
  Drug -- HealthInsurancePlan
  Drug -- Organization
  Drug -- DoseSchedule
  Drug -- DrugStrength


class Drug {

  DrugPregnancyCategory pregnancyCategory
  string overdosage
  DrugLegalStatus legalStatus
  string legalStatus
  MedicalEnumeration legalStatus
  string mechanismOfAction
  string clinicalPharmacology
  string rxcui
  Drug interactingDrug
  string dosageForm
  string labelDetails
  MaximumDoseSchedule maximumIntake
  string activeIngredient
  Drug relatedDrug
  string administrationRoute
  string drugUnit
  string foodWarning
  string warning
  string warning
  DrugPrescriptionStatus prescriptionStatus
  string prescriptionStatus
  string proprietaryName
  DrugClass drugClass
  string prescribingInfo
  HealthInsurancePlan includedInHealthInsurancePlan
  string nonProprietaryName
  Organization manufacturer
  boolean isProprietary
  string clincalPharmacology
  boolean isAvailableGenerically
  string breastfeedingWarning
  string pregnancyWarning
  string alcoholWarning
  DoseSchedule doseSchedule
  DrugStrength availableStrength

 }
