classDiagram
  EducationalOccupationalCredential -- Duration
EducationalOccupationalCredential -- string,DefinedTerm,string
EducationalOccupationalCredential -- Organization
EducationalOccupationalCredential -- AdministrativeArea


CreativeWork <|-- EducationalOccupationalCredential
class EducationalOccupationalCredential {

  Duration validFor
  string,DefinedTerm,string educationalLevel
  string,DefinedTerm,string credentialCategory
  Organization recognizedBy
  string,DefinedTerm,string competencyRequired
  AdministrativeArea validIn

}
