classDiagram
  EducationalOccupationalCredential -- Duration
  EducationalOccupationalCredential -- DefinedTerm
  EducationalOccupationalCredential -- Organization
  EducationalOccupationalCredential -- AdministrativeArea


class EducationalOccupationalCredential {

  Duration validFor
  string educationalLevel
  DefinedTerm educationalLevel
  string educationalLevel
  string credentialCategory
  DefinedTerm credentialCategory
  string credentialCategory
  Organization recognizedBy
  string competencyRequired
  DefinedTerm competencyRequired
  string competencyRequired
  AdministrativeArea validIn

 }
