classDiagram
  EducationEvent -- DefinedTerm


class EducationEvent {

  DefinedTerm teaches
  string teaches
  string educationalLevel
  DefinedTerm educationalLevel
  string educationalLevel
  string assesses
  DefinedTerm assesses

 }
