classDiagram
EnergyEfficiencyEnumeration o-- EUEnergyEfficiencyEnumeration
  class EUEnergyEfficiencyEnumeration {
<<enumeration>>
  o EUEnergyEfficiencyCategoryD
  o EUEnergyEfficiencyCategoryA2Plus
  o EUEnergyEfficiencyCategoryE
  o EUEnergyEfficiencyCategoryA3Plus
  o . . . 6 more values
}
