classDiagram
  ExchangeRateSpecification -- UnitPriceSpecification
ExchangeRateSpecification -- number,MonetaryAmount


StructuredValue <|-- ExchangeRateSpecification
class ExchangeRateSpecification {

  UnitPriceSpecification currentExchangeRate
  number,MonetaryAmount exchangeRateSpread
  string currency

}
