classDiagram
  ExchangeRateSpecification -- UnitPriceSpecification
  ExchangeRateSpecification -- MonetaryAmount


class ExchangeRateSpecification {

  UnitPriceSpecification currentExchangeRate
  number exchangeRateSpread
  MonetaryAmount exchangeRateSpread
  string currency

 }
