classDiagram
  Flight -- Distance
  Flight -- dateTime
  Flight -- Vehicle
  Flight -- Organization
  Flight -- Person
  Flight -- Airport
  Flight -- Duration
  Flight -- BoardingPolicyType


class Flight {

  Distance flightDistance
  string flightDistance
  dateTime webCheckinTime
  Vehicle aircraft
  string aircraft
  Organization seller
  Person seller
  Airport arrivalAirport
  string arrivalTerminal
  Airport departureAirport
  string arrivalGate
  string departureTerminal
  Organization carrier
  string estimatedFlightDuration
  Duration estimatedFlightDuration
  string departureGate
  string flightNumber
  string mealService
  BoardingPolicyType boardingPolicy

 }
