classDiagram
  FoodEstablishmentReservation -- QuantitativeValue
  FoodEstablishmentReservation -- dateTime
  FoodEstablishmentReservation -- time


class FoodEstablishmentReservation {

  number partySize
  QuantitativeValue partySize
  dateTime startTime
  time startTime
  dateTime endTime
  time endTime

 }
