classDiagram
  Game -- Thing
Game -- QuantitativeValue
Game -- Place,string,PostalAddress


CreativeWork <|-- Game
class Game {

  Thing characterAttribute
  Thing gameItem
  QuantitativeValue numberOfPlayers
  Thing quest
  Place,string,PostalAddress gameLocation

}
