classDiagram
  GeoCoordinates -- Country
  GeoCoordinates -- PostalAddress


class GeoCoordinates {

  Country addressCountry
  string addressCountry
  string latitude
  number latitude
  string address
  PostalAddress address
  string postalCode
  string elevation
  number elevation
  number longitude
  string longitude

 }
