classDiagram
  GeoShape -- Country,string
GeoShape -- string,PostalAddress
GeoShape -- string,number


StructuredValue <|-- GeoShape
class GeoShape {

  Country,string addressCountry
  string circle
  string line
  string polygon
  string,PostalAddress address
  string postalCode
  string,number elevation
  string box

}
