classDiagram
  GiveAction -- Person
  GiveAction -- Audience
  GiveAction -- ContactPoint
  GiveAction -- Organization


class GiveAction {

  Person recipient
  Audience recipient
  ContactPoint recipient
  Organization recipient

 }
