classDiagram
  GovernmentService -- AdministrativeArea
  GovernmentService -- Organization


class GovernmentService {

  string jurisdiction
  AdministrativeArea jurisdiction
  Organization serviceOperator

 }
