classDiagram
Enumeration o-- GovernmentBenefitsType
  class GovernmentBenefitsType {
<<enumeration>>
  o HealthCare
  o BusinessSupport
  o OneTimePayments
  o DisabilitySupport
  o . . . 4 more values
}
