classDiagram
Enumeration o-- HealthAspectEnumeration
  class HealthAspectEnumeration {
<<enumeration>>
  o SideEffectsHealthAspect
  o AllergiesHealthAspect
  o BenefitsHealthAspect
  o SymptomsHealthAspect
  o . . . 25 more values
}
