classDiagram
  Hospital -- MedicalTest
  Hospital -- MedicalProcedure
  Hospital -- MedicalTherapy
  Hospital -- Dataset
  Hospital -- CDCPMDRecord
  Hospital -- MedicalSpecialty


class Hospital {

  MedicalTest availableService
  MedicalProcedure availableService
  MedicalTherapy availableService
  Dataset healthcareReportingData
  CDCPMDRecord healthcareReportingData
  MedicalSpecialty medicalSpecialty

 }
