classDiagram
  ImageObject -- string,MediaObject
ImageObject -- ImageObject
ImageObject -- PropertyValue,string


MediaObject <|-- ImageObject
class ImageObject {

  string embeddedTextCaption
  boolean representativeOfPage
  string,MediaObject caption
  ImageObject thumbnail
  PropertyValue,string exifData

}
