classDiagram
  InfectiousDisease -- InfectiousAgentClass


MedicalCondition <|-- InfectiousDisease
class InfectiousDisease {

  InfectiousAgentClass infectiousAgentClass
  string infectiousAgent
  string transmissionMethod

}
