classDiagram
  InsurancePerson -- PersonRelationToPolicyHolderEnum


Person <|-- InsurancePerson
class InsurancePerson {

  PersonRelationToPolicyHolderEnum relationToPolicyHolder
  string firstName
  string lastName
  number age

}
