classDiagram
  InsurancePolicy -- Coverage
  InsurancePolicy -- RiskObject
  InsurancePolicy -- Specific


class InsurancePolicy {

  Coverage[] coverages
  RiskObject[] riskObjects
  Specific[] specifics

 }
