classDiagram
  InsuranceVehicle -- Amount


Vehicle <|-- InsuranceVehicle
class InsuranceVehicle {

  Amount productionYear
  Amount age
  Amount length
  Amount weight
  Amount height
  Amount width

}
