classDiagram
  InsurancePerson -- PersonRelationToPolicyHolderEnum


class InsurancePerson {

  PersonRelationToPolicyHolderEnum relationToPolicyHolder
  string firstName
  string lastName
  number age

 }
