classDiagram
  InsurancePayout -- PayoutTypeEnum
  InsurancePayout -- Amount
  InsurancePayout -- Multiplier
  InsurancePayout -- RiskChain


class InsurancePayout {

  PayoutTypeEnum payoutType
  Amount[] amount
  Amount[] minimalAmount
  Multiplier per
  RiskChain for
  boolean impactOtherConsumption

 }
