classDiagram
  InteractionCounter -- dateTime
  InteractionCounter -- time
  InteractionCounter -- PostalAddress
  InteractionCounter -- Place
  InteractionCounter -- VirtualLocation
  InteractionCounter -- Action
  InteractionCounter -- SoftwareApplication
  InteractionCounter -- WebSite


class InteractionCounter {

  dateTime startTime
  time startTime
  number userInteractionCount
  PostalAddress location
  string location
  Place location
  VirtualLocation location
  Action interactionType
  SoftwareApplication interactionService
  WebSite interactionService
  dateTime endTime
  time endTime

 }
