classDiagram
  Legislation -- Legislation
  Legislation -- LegalForceStatus
  Legislation -- CategoryCode
  Legislation -- AdministrativeArea
  Legislation -- Organization
  Legislation -- Person
  Legislation -- date


class Legislation {

  Legislation legislationTransposes
  LegalForceStatus legislationLegalForce
  CategoryCode legislationType
  string legislationType
  string jurisdiction
  AdministrativeArea jurisdiction
  string legislationIdentifier
  string legislationIdentifier
  Legislation legislationChanges
  Organization legislationResponsible
  Person legislationResponsible
  AdministrativeArea legislationJurisdiction
  string legislationJurisdiction
  date legislationDate
  Person legislationPassedBy
  Organization legislationPassedBy
  Legislation legislationConsolidates
  Legislation legislationApplies
  date legislationDateVersion

 }
