classDiagram
  ListItem -- number,string
ListItem -- ListItem
ListItem -- Thing


Intangible <|-- ListItem
class ListItem {

  number,string position
  ListItem nextItem
  Thing item
  ListItem previousItem

}
