classDiagram
  LoanOrCredit -- QuantitativeValue
  LoanOrCredit -- Duration
  LoanOrCredit -- Thing
  LoanOrCredit -- MonetaryAmount
  LoanOrCredit -- RepaymentSpecification


class LoanOrCredit {

  boolean renegotiableLoan
  string loanType
  string loanType
  boolean recourseLoan
  QuantitativeValue loanTerm
  Duration gracePeriod
  string requiredCollateral
  Thing requiredCollateral
  string currency
  number amount
  MonetaryAmount amount
  RepaymentSpecification loanRepaymentForm

 }
