classDiagram
  LoanOrCredit -- string,string
LoanOrCredit -- QuantitativeValue
LoanOrCredit -- Duration
LoanOrCredit -- string,Thing
LoanOrCredit -- number,MonetaryAmount
LoanOrCredit -- RepaymentSpecification


FinancialProduct <|-- LoanOrCredit
class LoanOrCredit {

  boolean renegotiableLoan
  string,string loanType
  boolean recourseLoan
  QuantitativeValue loanTerm
  Duration gracePeriod
  string,Thing requiredCollateral
  string currency
  number,MonetaryAmount amount
  RepaymentSpecification loanRepaymentForm

}
