classDiagram
  LodgingReservation -- QualitativeValue
  LodgingReservation -- dateTime
  LodgingReservation -- time
  LodgingReservation -- QuantitativeValue


class LodgingReservation {

  QualitativeValue lodgingUnitType
  string lodgingUnitType
  string lodgingUnitDescription
  dateTime checkoutTime
  time checkoutTime
  number numAdults
  QuantitativeValue numAdults
  dateTime checkinTime
  time checkinTime
  number numChildren
  QuantitativeValue numChildren

 }
