classDiagram
  LymphaticVessel -- Vessel
LymphaticVessel -- AnatomicalSystem,AnatomicalStructure


Vessel <|-- LymphaticVessel
class LymphaticVessel {

  Vessel runsTo
  AnatomicalSystem,AnatomicalStructure regionDrained
  Vessel originatesFrom

}
