classDiagram
  LymphaticVessel -- Vessel
  LymphaticVessel -- AnatomicalSystem
  LymphaticVessel -- AnatomicalStructure


class LymphaticVessel {

  Vessel runsTo
  AnatomicalSystem regionDrained
  AnatomicalStructure regionDrained
  Vessel originatesFrom

 }
