classDiagram
MedicalEnumeration o-- MedicalTrialDesign
  class MedicalTrialDesign {
<<enumeration>>
  o PlaceboControlledTrial
  o DoubleBlindedTrial
  o MultiCenterTrial
  o InternationalTrial
  o . . . 5 more values
}
