classDiagram
  MedicalRiskEstimator -- MedicalEntity
MedicalRiskEstimator -- MedicalRiskFactor


MedicalEntity <|-- MedicalRiskEstimator
class MedicalRiskEstimator {

  MedicalEntity estimatesRiskOf
  MedicalRiskFactor includedRiskFactor

}
