classDiagram
  MedicalObservationalStudy -- MedicalObservationalStudyDesign


MedicalStudy <|-- MedicalObservationalStudy
class MedicalObservationalStudy {

  MedicalObservationalStudyDesign studyDesign

}
