classDiagram
  MedicalClinic -- MedicalTest
  MedicalClinic -- MedicalProcedure
  MedicalClinic -- MedicalTherapy
  MedicalClinic -- MedicalSpecialty


class MedicalClinic {

  MedicalTest availableService
  MedicalProcedure availableService
  MedicalTherapy availableService
  MedicalSpecialty medicalSpecialty

 }
