classDiagram
  MedicalSpecialty -- schema:MedicalSpecialty


class MedicalSpecialty {

  schema:MedicalSpecialty Cardiovascular
  schema:MedicalSpecialty Renal
  schema:MedicalSpecialty Nursing
  schema:MedicalSpecialty Dermatologic
  schema:MedicalSpecialty DietNutrition
  schema:MedicalSpecialty PrimaryCare
  schema:MedicalSpecialty Oncologic
  schema:MedicalSpecialty Physiotherapy
  schema:MedicalSpecialty Optometric
  schema:MedicalSpecialty Gynecologic
  schema:MedicalSpecialty Midwifery
  schema:MedicalSpecialty SpeechPathology
  schema:MedicalSpecialty CommunityHealth
  schema:MedicalSpecialty Emergency
  schema:MedicalSpecialty LaboratoryScience
  schema:MedicalSpecialty Geriatric
  schema:MedicalSpecialty Anesthesia
  schema:MedicalSpecialty Endocrine
  schema:MedicalSpecialty RespiratoryTherapy
  schema:MedicalSpecialty Pediatric
  schema:MedicalSpecialty Genetic
  schema:MedicalSpecialty Infectious
  schema:MedicalSpecialty Rheumatologic
  schema:MedicalSpecialty Musculoskeletal
  schema:MedicalSpecialty Podiatric
  schema:MedicalSpecialty Obstetric
  schema:MedicalSpecialty Pathology
  schema:MedicalSpecialty Pulmonary
  schema:MedicalSpecialty Dermatology
  schema:MedicalSpecialty Dentistry
  schema:MedicalSpecialty Gastroenterologic
  schema:MedicalSpecialty PublicHealth
  schema:MedicalSpecialty Psychiatric
  schema:MedicalSpecialty PharmacySpecialty
  schema:MedicalSpecialty Hematologic
  schema:MedicalSpecialty Toxicologic
  schema:MedicalSpecialty PlasticSurgery
  schema:MedicalSpecialty Urologic
  schema:MedicalSpecialty Neurologic
  schema:MedicalSpecialty Otolaryngologic
  schema:MedicalSpecialty Surgical

 }
