classDiagram
  MedicalTherapy -- MedicalTherapy
  MedicalTherapy -- MedicalEntity
  MedicalTherapy -- MedicalContraindication


class MedicalTherapy {

  MedicalTherapy duplicateTherapy
  MedicalEntity seriousAdverseOutcome
  string contraindication
  MedicalContraindication contraindication

 }
