classDiagram
  MenuItem -- MenuItem
  MenuItem -- MenuSection
  MenuItem -- Offer
  MenuItem -- Demand
  MenuItem -- RestrictedDiet
  MenuItem -- NutritionInformation


class MenuItem {

  MenuItem menuAddOn
  MenuSection menuAddOn
  Offer offers
  Demand offers
  RestrictedDiet suitableForDiet
  NutritionInformation nutrition

 }
