classDiagram
Enumeration o-- MerchantReturnEnumeration
  class MerchantReturnEnumeration {
<<enumeration>>
  o MerchantReturnNotPermitted
  o MerchantReturnUnlimitedWindow
  o MerchantReturnFiniteReturnWindow
  o MerchantReturnUnspecified
}
