classDiagram
  MoneyTransfer -- BankOrCreditUnion,string
MoneyTransfer -- number,MonetaryAmount


TransferAction <|-- MoneyTransfer
class MoneyTransfer {

  BankOrCreditUnion,string beneficiaryBank
  number,MonetaryAmount amount

}
