classDiagram
  Multiplier -- MultiplierTimeEnum
Multiplier -- MultiplierPersonEnum
Multiplier -- MultiplierOccurenceEnum
Multiplier -- MultiplierInsuredObjectEnum


class Multiplier {

  MultiplierTimeEnum time
  MultiplierPersonEnum person
  MultiplierOccurenceEnum occurence
  MultiplierInsuredObjectEnum insuredObject

}
