classDiagram
  Multiplier -- MultiplierTimeEnum
Multiplier -- MultiplierPersonEnum
Multiplier -- MultiplierOccurrenceEnum
Multiplier -- MultiplierInsuredObjectEnum


class Multiplier {

  MultiplierTimeEnum time
  MultiplierPersonEnum person
  MultiplierOccurrenceEnum occurrence
  MultiplierInsuredObjectEnum insuredObject
  string[] other

}
