classDiagram
  Muscle -- AnatomicalStructure
  Muscle -- Muscle
  Muscle -- Nerve
  Muscle -- Vessel


class Muscle {

  AnatomicalStructure insertion
  Muscle antagonist
  Nerve nerve
  Vessel bloodSupply
  string muscleAction

 }
