classDiagram
Enumeration o-- MusicReleaseFormatType
  class MusicReleaseFormatType {
<<enumeration>>
  o CDFormat
  o DigitalAudioTapeFormat
  o DigitalFormat
  o LaserDiscFormat
  o . . . 3 more values
}
