classDiagram
  MusicGroup -- MusicRecording
MusicGroup -- string,string
MusicGroup -- Person
MusicGroup -- MusicAlbum
MusicGroup -- ItemList,MusicRecording


PerformingGroup <|-- MusicGroup
class MusicGroup {

  MusicRecording tracks
  string,string genre
  Person musicGroupMember
  MusicAlbum albums
  ItemList,MusicRecording track
  MusicAlbum album

}
