classDiagram
  MusicGroup -- MusicRecording
  MusicGroup -- Person
  MusicGroup -- MusicAlbum
  MusicGroup -- ItemList


class MusicGroup {

  MusicRecording tracks
  string genre
  string genre
  Person musicGroupMember
  MusicAlbum albums
  ItemList track
  MusicRecording track
  MusicAlbum album

 }
