classDiagram
  MusicAlbum -- MusicAlbumProductionType
  MusicAlbum -- MusicAlbumReleaseType
  MusicAlbum -- MusicRelease
  MusicAlbum -- Person
  MusicAlbum -- MusicGroup


class MusicAlbum {

  MusicAlbumProductionType albumProductionType
  MusicAlbumReleaseType albumReleaseType
  MusicRelease albumRelease
  Person byArtist
  MusicGroup byArtist

 }
