classDiagram
  MusicPlaylist -- MusicRecording
MusicPlaylist -- ItemList,MusicRecording


CreativeWork <|-- MusicPlaylist
class MusicPlaylist {

  MusicRecording tracks
  number numTracks
  ItemList,MusicRecording track

}
