classDiagram
  Nerve -- SuperficialAnatomy,AnatomicalStructure
Nerve -- AnatomicalStructure
Nerve -- BrainStructure
Nerve -- Muscle


AnatomicalStructure <|-- Nerve
class Nerve {

  SuperficialAnatomy,AnatomicalStructure sensoryUnit
  AnatomicalStructure branch
  BrainStructure sourcedFrom
  Muscle nerveMotor

}
