classDiagram
  Nerve -- SuperficialAnatomy
  Nerve -- AnatomicalStructure
  Nerve -- BrainStructure
  Nerve -- Muscle


class Nerve {

  SuperficialAnatomy sensoryUnit
  AnatomicalStructure sensoryUnit
  AnatomicalStructure branch
  BrainStructure sourcedFrom
  Muscle nerveMotor

 }
