classDiagram
  NLNonprofitType -- schema:NLNonprofitType


NonprofitType <|-- NLNonprofitType
class NLNonprofitType {

  schema:NLNonprofitType NonprofitANBI
  schema:NLNonprofitType NonprofitSBBI

}
