classDiagram
  NutritionInformation -- Mass
  NutritionInformation -- Energy


class NutritionInformation {

  Mass fatContent
  string servingSize
  Mass proteinContent
  Energy calories
  Mass sodiumContent
  Mass cholesterolContent
  Mass sugarContent
  Mass carbohydrateContent
  Mass transFatContent
  Mass fiberContent
  Mass unsaturatedFatContent
  Mass saturatedFatContent

 }
