classDiagram
  Observation -- DataType
  Observation -- StatisticalPopulation
  Observation -- Property
  Observation -- dateTime
  Observation -- QuantitativeValue


class Observation {

  DataType measuredValue
  StatisticalPopulation observedNode
  Property measuredProperty
  dateTime observationDate
  QuantitativeValue marginOfError

 }
