classDiagram
  OrderItem -- ParcelDelivery
  OrderItem -- OrderStatus
  OrderItem -- Service
  OrderItem -- OrderItem
  OrderItem -- Product


class OrderItem {

  ParcelDelivery orderDelivery
  OrderStatus orderItemStatus
  number orderQuantity
  string orderItemNumber
  Service orderedItem
  OrderItem orderedItem
  Product orderedItem

 }
