classDiagram
  Order -- ParcelDelivery
  Order -- PostalAddress
  Order -- Offer
  Order -- Organization
  Order -- Person
  Order -- OrderStatus
  Order -- Invoice
  Order -- dateTime
  Order -- date
  Order -- Service
  Order -- OrderItem
  Order -- Product
  Order -- PaymentMethod


class Order {

  ParcelDelivery orderDelivery
  PostalAddress billingAddress
  Offer acceptedOffer
  Organization merchant
  Person merchant
  OrderStatus orderStatus
  string confirmationNumber
  Invoice partOfInvoice
  string orderNumber
  Organization seller
  Person seller
  Organization customer
  Person customer
  dateTime paymentDueDate
  date paymentDueDate
  Person broker
  Organization broker
  string discountCode
  string discount
  number discount
  string paymentMethodId
  string paymentUrl
  string discountCurrency
  dateTime paymentDue
  date orderDate
  dateTime orderDate
  boolean isGift
  Service orderedItem
  OrderItem orderedItem
  Product orderedItem
  PaymentMethod paymentMethod

 }
