classDiagram
  ParcelDelivery -- PostalAddress
ParcelDelivery -- Product
ParcelDelivery -- Organization,Person
ParcelDelivery -- date,dateTime
ParcelDelivery -- DeliveryEvent
ParcelDelivery -- Organization
ParcelDelivery -- DeliveryMethod
ParcelDelivery -- Order


Intangible <|-- ParcelDelivery
class ParcelDelivery {

  PostalAddress originAddress
  string trackingNumber
  Product itemShipped
  Organization,Person provider
  string trackingUrl
  PostalAddress deliveryAddress
  date,dateTime expectedArrivalUntil
  DeliveryEvent deliveryStatus
  date,dateTime expectedArrivalFrom
  Organization carrier
  DeliveryMethod hasDeliveryMethod
  Order partOfOrder

}
