classDiagram
  ParcelDelivery -- PostalAddress
  ParcelDelivery -- Product
  ParcelDelivery -- Organization
  ParcelDelivery -- Person
  ParcelDelivery -- date
  ParcelDelivery -- dateTime
  ParcelDelivery -- DeliveryEvent
  ParcelDelivery -- DeliveryMethod
  ParcelDelivery -- Order


class ParcelDelivery {

  PostalAddress originAddress
  string trackingNumber
  Product itemShipped
  Organization provider
  Person provider
  string trackingUrl
  PostalAddress deliveryAddress
  date expectedArrivalUntil
  dateTime expectedArrivalUntil
  DeliveryEvent deliveryStatus
  date expectedArrivalFrom
  dateTime expectedArrivalFrom
  Organization carrier
  DeliveryMethod hasDeliveryMethod
  Order partOfOrder

 }
