classDiagram
  PaymentChargeSpecification -- PaymentMethod
PaymentChargeSpecification -- DeliveryMethod


PriceSpecification <|-- PaymentChargeSpecification
class PaymentChargeSpecification {

  PaymentMethod appliesToPaymentMethod
  DeliveryMethod appliesToDeliveryMethod

}
