classDiagram
  PaymentChargeSpecification -- PaymentMethod
  PaymentChargeSpecification -- DeliveryMethod


class PaymentChargeSpecification {

  PaymentMethod appliesToPaymentMethod
  DeliveryMethod appliesToDeliveryMethod

 }
