classDiagram
class PayoutScopeServiceEnum {
<<enumeration>>
  o indemnity
  o legalCost
  o legalExpenses
  o bailsBond
  o windscreenRepair
  o windscreenReplacement
  o carStorageFee
  o travelingCost
  o courtesyCar
  o carHire
  o alternativeTransport
  o towing
  o overnightAccomodation
  o bedAndBreakfast
}
