classDiagram
  Person -- Person
  Person -- EducationalOccupationalCredential
  Person -- Thing
  Person -- Event
  Person -- MonetaryAmount
  Person -- PriceSpecification
  Person -- Place
  Person -- ContactPoint
  Person -- Grant
  Person -- Distance
  Person -- QuantitativeValue
  Person -- Occupation
  Person -- GenderType
  Person -- DefinedTerm
  Person -- date
  Person -- Organization
  Person -- Offer
  Person -- InteractionCounter
  Person -- PostalAddress
  Person -- ProgramMembership
  Person -- CreativeWork
  Person -- Brand
  Person -- EducationalOrganization
  Person -- Language
  Person -- Demand
  Person -- Product
  Person -- OwnershipInfo
  Person -- OfferCatalog
  Person -- Country


class Person {

  Person spouse
  string additionalName
  EducationalOccupationalCredential hasCredential
  string telephone
  string honorificPrefix
  Person parents
  string familyName
  string givenName
  string knowsAbout
  string knowsAbout
  Thing knowsAbout
  Event performerIn
  MonetaryAmount netWorth
  PriceSpecification netWorth
  string award
  Place workLocation
  ContactPoint workLocation
  string honorificSuffix
  Place deathPlace
  Place homeLocation
  ContactPoint homeLocation
  Grant funding
  string vatID
  Distance height
  QuantitativeValue height
  string globalLocationNumber
  ContactPoint contactPoints
  Occupation hasOccupation
  GenderType gender
  string gender
  Person parent
  string awards
  Person sibling
  string jobTitle
  DefinedTerm jobTitle
  date birthDate
  Organization funder
  Person funder
  Offer makesOffer
  Person children
  Organization worksFor
  Person knows
  InteractionCounter interactionStatistic
  string address
  PostalAddress address
  ProgramMembership memberOf
  Organization memberOf
  string publishingPrinciples
  CreativeWork publishingPrinciples
  Person colleagues
  date deathDate
  string email
  Organization affiliation
  Person siblings
  Place birthPlace
  Organization brand
  Brand brand
  Organization sponsor
  Person sponsor
  string naics
  ContactPoint contactPoint
  string callSign
  string isicV4
  Place hasPOS
  EducationalOrganization alumniOf
  Organization alumniOf
  string duns
  QuantitativeValue weight
  Language knowsLanguage
  string knowsLanguage
  Person relatedTo
  Person colleague
  string colleague
  Demand seeks
  string taxID
  Product owns
  OwnershipInfo owns
  OfferCatalog hasOfferCatalog
  Person follows
  Country nationality
  string faxNumber

 }
