classDiagram
  Person -- Person
Person -- EducationalOccupationalCredential
Person -- string,string,Thing
Person -- Event
Person -- MonetaryAmount,PriceSpecification
Person -- Place,ContactPoint
Person -- Place
Person -- Grant
Person -- Distance,QuantitativeValue
Person -- ContactPoint
Person -- Occupation
Person -- GenderType,string
Person -- string,DefinedTerm
Person -- date
Person -- Organization,Person
Person -- Offer
Person -- Organization
Person -- InteractionCounter
Person -- string,PostalAddress
Person -- ProgramMembership,Organization
Person -- string,CreativeWork
Person -- Organization,Brand
Person -- EducationalOrganization,Organization
Person -- QuantitativeValue
Person -- Language,string
Person -- Person,string
Person -- Demand
Person -- Product,OwnershipInfo
Person -- OfferCatalog
Person -- Country


Thing <|-- Person
class Person {

  Person spouse
  string additionalName
  EducationalOccupationalCredential hasCredential
  string telephone
  string honorificPrefix
  Person parents
  string familyName
  string givenName
  string,string,Thing knowsAbout
  Event performerIn
  MonetaryAmount,PriceSpecification netWorth
  string award
  Place,ContactPoint workLocation
  string honorificSuffix
  Place deathPlace
  Place,ContactPoint homeLocation
  Grant funding
  string vatID
  Distance,QuantitativeValue height
  string globalLocationNumber
  ContactPoint contactPoints
  Occupation hasOccupation
  GenderType,string gender
  Person parent
  string awards
  Person sibling
  string,DefinedTerm jobTitle
  date birthDate
  Organization,Person funder
  Offer makesOffer
  Person children
  Organization worksFor
  Person knows
  InteractionCounter interactionStatistic
  string,PostalAddress address
  ProgramMembership,Organization memberOf
  string,CreativeWork publishingPrinciples
  Person colleagues
  date deathDate
  string email
  Organization affiliation
  Person siblings
  Place birthPlace
  Organization,Brand brand
  Organization,Person sponsor
  string naics
  ContactPoint contactPoint
  string callSign
  string isicV4
  Place hasPOS
  EducationalOrganization,Organization alumniOf
  string duns
  QuantitativeValue weight
  Language,string knowsLanguage
  Person relatedTo
  Person,string colleague
  Demand seeks
  string taxID
  Product,OwnershipInfo owns
  OfferCatalog hasOfferCatalog
  Person follows
  Country nationality
  string faxNumber

}
