classDiagram
  Person -- PersonRelationToPolicyHolderEnum


RiskObject <|-- Person
class Person {

  PersonRelationToPolicyHolderEnum relationToPolicyHolder
  string firstName
  string lastName
  number age

}
