classDiagram
  PhysicalExam -- schema:PhysicalExam


class PhysicalExam {

  schema:PhysicalExam Genitourinary
  schema:PhysicalExam Abdomen
  schema:PhysicalExam Appearance
  schema:PhysicalExam CardiovascularExam
  schema:PhysicalExam Skin
  schema:PhysicalExam Lung
  schema:PhysicalExam Neck
  schema:PhysicalExam Ear
  schema:PhysicalExam MusculoskeletalExam
  schema:PhysicalExam Head
  schema:PhysicalExam Eye
  schema:PhysicalExam Throat
  schema:PhysicalExam Neuro
  schema:PhysicalExam Nose

 }
