classDiagram
  PhysicalExam -- PhysicalExam


class PhysicalExam {

  PhysicalExam Genitourinary
  PhysicalExam Abdomen
  PhysicalExam Appearance
  PhysicalExam CardiovascularExam
  PhysicalExam Skin
  PhysicalExam Lung
  PhysicalExam Neck
  PhysicalExam Ear
  PhysicalExam MusculoskeletalExam
  PhysicalExam Head
  PhysicalExam Eye
  PhysicalExam Throat
  PhysicalExam Neuro
  PhysicalExam Nose

 }
