classDiagram
  PostalAddress -- Country


class PostalAddress {

  Country addressCountry
  string addressCountry
  string addressRegion
  string addressLocality
  string postalCode
  string postOfficeBoxNumber
  string streetAddress

 }
