classDiagram
Enumeration o-- PriceComponentTypeEnumeration
  class PriceComponentTypeEnumeration {
<<enumeration>>
  o Subscription
  o Installment
  o ActivationFee
  o Downpayment
  o . . . 2 more values
}
