classDiagram
  Product -- Product
  Product -- AdultOrientedEnumeration
  Product -- Review
  Product -- QuantitativeValue
  Product -- Distance
  Product -- Country
  Product -- DefinedTerm
  Product -- PhysicalActivityCategory
  Product -- Thing
  Product -- CategoryCode
  Product -- Grant
  Product -- date
  Product -- EnergyConsumptionDetails
  Product -- Audience
  Product -- Offer
  Product -- Demand
  Product -- OfferItemCondition
  Product -- AggregateRating
  Product -- Service
  Product -- ProductModel
  Product -- ProductGroup
  Product -- Organization
  Product -- Brand
  Product -- ImageObject
  Product -- MerchantReturnPolicy
  Product -- SizeSpecification
  Product -- PropertyValue


class Product {

  Product isAccessoryOrSparePartFor
  AdultOrientedEnumeration hasAdultConsideration
  string gtin12
  string nsn
  string material
  string material
  Product material
  Review review
  string award
  QuantitativeValue width
  Distance width
  Country countryOfOrigin
  DefinedTerm pattern
  string pattern
  string category
  string category
  PhysicalActivityCategory category
  Thing category
  CategoryCode category
  Grant funding
  string mpn
  Distance height
  QuantitativeValue height
  DefinedTerm keywords
  string keywords
  string keywords
  date purchaseDate
  EnergyConsumptionDetails hasEnergyConsumptionDetails
  Audience audience
  Offer offers
  Demand offers
  date productionDate
  OfferItemCondition itemCondition
  string awards
  string gtin
  string productID
  string countryOfAssembly
  string color
  AggregateRating aggregateRating
  Service isSimilarTo
  Product isSimilarTo
  Distance depth
  QuantitativeValue depth
  string countryOfLastProcessing
  ProductModel isVariantOf
  ProductGroup isVariantOf
  string slogan
  Organization brand
  Brand brand
  Organization manufacturer
  QuantitativeValue hasMeasurement
  Product isConsumableFor
  string logo
  ImageObject logo
  string gtin8
  string sku
  string inProductGroupWithID
  ProductModel model
  string model
  MerchantReturnPolicy hasMerchantReturnPolicy
  date releaseDate
  string gtin14
  QuantitativeValue weight
  QuantitativeValue size
  DefinedTerm size
  string size
  SizeSpecification size
  PropertyValue additionalProperty
  string gtin13
  Review reviews
  boolean isFamilyFriendly
  Service isRelatedTo
  Product isRelatedTo

 }
