classDiagram
  ProgramMembership -- QuantitativeValue
  ProgramMembership -- Organization
  ProgramMembership -- Person


class ProgramMembership {

  number membershipPointsEarned
  QuantitativeValue membershipPointsEarned
  Organization member
  Person member
  string membershipNumber
  Organization hostingOrganization
  string programName
  Person members
  Organization members

 }
