classDiagram
  PronounceableText -- Language


  string <|-- PronounceableText
class PronounceableText {

  string phoneticText
  string speechToTextMarkup
  string textValue
  string inLanguage
  Language inLanguage

 }
