classDiagram
  PropertyValue -- Enumeration
  PropertyValue -- DefinedTerm
  PropertyValue -- MeasurementTypeEnumeration
  PropertyValue -- QualitativeValue
  PropertyValue -- StructuredValue
  PropertyValue -- PropertyValue
  PropertyValue -- QuantitativeValue


class PropertyValue {

  Enumeration valueReference
  DefinedTerm valueReference
  string valueReference
  MeasurementTypeEnumeration valueReference
  QualitativeValue valueReference
  StructuredValue valueReference
  PropertyValue valueReference
  QuantitativeValue valueReference
  string propertyID
  string propertyID
  number maxValue
  string unitText
  string measurementTechnique
  string measurementTechnique
  number minValue
  string value
  number value
  StructuredValue value
  boolean value
  string unitCode
  string unitCode

 }
