classDiagram
  PublicationEvent -- Organization
  PublicationEvent -- Person
  PublicationEvent -- BroadcastService


class PublicationEvent {

  Organization publishedBy
  Person publishedBy
  boolean free
  BroadcastService publishedOn

 }
