classDiagram
  QuantitativeValue -- Enumeration
  QuantitativeValue -- DefinedTerm
  QuantitativeValue -- MeasurementTypeEnumeration
  QuantitativeValue -- QualitativeValue
  QuantitativeValue -- StructuredValue
  QuantitativeValue -- PropertyValue
  QuantitativeValue -- QuantitativeValue


class QuantitativeValue {

  Enumeration valueReference
  DefinedTerm valueReference
  string valueReference
  MeasurementTypeEnumeration valueReference
  QualitativeValue valueReference
  StructuredValue valueReference
  PropertyValue valueReference
  QuantitativeValue valueReference
  number maxValue
  string unitText
  number minValue
  string value
  number value
  StructuredValue value
  boolean value
  string unitCode
  string unitCode
  PropertyValue additionalProperty

 }
