classDiagram
  QuantitativeValueDistribution -- Duration


class QuantitativeValueDistribution {

  number percentile75
  number median
  number percentile10
  number percentile25
  number percentile90
  Duration duration

 }
