classDiagram
  Question -- ItemList
  Question -- Answer


class Question {

  ItemList suggestedAnswer
  Answer suggestedAnswer
  Answer acceptedAnswer
  ItemList acceptedAnswer
  number answerCount
  string eduQuestionType

 }
