classDiagram
  RadioSeries -- CreativeWorkSeason
  RadioSeries -- Person
  RadioSeries -- VideoObject
  RadioSeries -- Episode
  RadioSeries -- Organization
  RadioSeries -- MusicGroup


class RadioSeries {

  string season
  CreativeWorkSeason season
  CreativeWorkSeason containsSeason
  Person director
  Person actor
  VideoObject trailer
  Episode episodes
  number numberOfEpisodes
  CreativeWorkSeason seasons
  Organization productionCompany
  Person actors
  number numberOfSeasons
  Person musicBy
  MusicGroup musicBy
  Episode episode
  Person directors

 }
