classDiagram
  Rating -- string,number
Rating -- Person,Organization
Rating -- number,string


Intangible <|-- Rating
class Rating {

  string reviewAspect
  string,number worstRating
  Person,Organization author
  string,number bestRating
  number,string ratingValue
  string ratingExplanation

}
