classDiagram
  RealEstateListing -- QuantitativeValue
  RealEstateListing -- Duration
  RealEstateListing -- date
  RealEstateListing -- dateTime


class RealEstateListing {

  QuantitativeValue leaseLength
  Duration leaseLength
  date datePosted
  dateTime datePosted

 }
