classDiagram
  ReceiveAction -- Person,Audience,Organization
ReceiveAction -- DeliveryMethod


TransferAction <|-- ReceiveAction
class ReceiveAction {

  Person,Audience,Organization sender
  DeliveryMethod deliveryMethod

}
