classDiagram
  Recipe -- CreativeWork
  Recipe -- ItemList
  Recipe -- RestrictedDiet
  Recipe -- NutritionInformation
  Recipe -- QuantitativeValue
  Recipe -- Duration


class Recipe {

  string recipeInstructions
  CreativeWork recipeInstructions
  ItemList recipeInstructions
  string ingredients
  string recipeCuisine
  RestrictedDiet suitableForDiet
  NutritionInformation nutrition
  string cookingMethod
  string recipeIngredient
  string recipeYield
  QuantitativeValue recipeYield
  Duration cookTime
  string recipeCategory

 }
