classDiagram
  Recommendation -- PhysicalActivityCategory
  Recommendation -- Thing
  Recommendation -- CategoryCode


class Recommendation {

  string category
  string category
  PhysicalActivityCategory category
  Thing category
  CategoryCode category

 }
