classDiagram
  Recommendation -- string,string,PhysicalActivityCategory,Thing,CategoryCode


Review <|-- Recommendation
class Recommendation {

  string,string,PhysicalActivityCategory,Thing,CategoryCode category

}
