classDiagram
  Reservation -- dateTime
  Reservation -- PriceSpecification
  Reservation -- Ticket
  Reservation -- ReservationStatusType
  Reservation -- Organization
  Reservation -- Person
  Reservation -- ProgramMembership
  Reservation -- Thing


class Reservation {

  dateTime modifiedTime
  PriceSpecification totalPrice
  number totalPrice
  string totalPrice
  Ticket reservedTicket
  ReservationStatusType reservationStatus
  Organization provider
  Person provider
  Person broker
  Organization broker
  dateTime bookingTime
  ProgramMembership programMembershipUsed
  Person bookingAgent
  Organization bookingAgent
  string priceCurrency
  string reservationId
  Organization underName
  Person underName
  Thing reservationFor

 }
