classDiagram
StatusEnumeration o-- ReservationStatusType
  class ReservationStatusType {
<<enumeration>>
  o ReservationPending
  o ReservationConfirmed
  o ReservationCancelled
  o ReservationHold
}
