classDiagram
Enumeration o-- ReturnLabelSourceEnumeration
  class ReturnLabelSourceEnumeration {
<<enumeration>>
  o ReturnLabelCustomerResponsibility
  o ReturnLabelDownloadAndPrint
  o ReturnLabelInBox
}
