classDiagram
  ReturnAction -- Person
  ReturnAction -- Audience
  ReturnAction -- ContactPoint
  ReturnAction -- Organization


class ReturnAction {

  Person recipient
  Audience recipient
  ContactPoint recipient
  Organization recipient

 }
