classDiagram
  Review -- Rating
  Review -- Thing
  Review -- ListItem
  Review -- WebContent
  Review -- ItemList
  Review -- Review


class Review {

  Rating reviewRating
  Thing itemReviewed
  ListItem negativeNotes
  string negativeNotes
  WebContent negativeNotes
  ItemList negativeNotes
  string reviewAspect
  Review associatedClaimReview
  WebContent positiveNotes
  string positiveNotes
  ListItem positiveNotes
  ItemList positiveNotes
  Review associatedReview
  Review associatedMediaReview
  string reviewBody

 }
