classDiagram
  RiskChain -- RiskChainActor
RiskChain -- RiskChainSituation
RiskChain -- RiskChainLogicNode
RiskChain -- RiskChainEdge
RiskChain -- RiskChainLogicEdge


class RiskChain {

  RiskChainActor[] actors
  RiskChainSituation[] situations
  RiskChainLogicNode[] logicNode
  RiskChainEdge[] relations
  RiskChainLogicEdge[] logicRelation

}
