classDiagram
  RsvpAction -- RsvpResponseType
RsvpAction -- Comment


InformAction <|-- RsvpAction
class RsvpAction {

  RsvpResponseType rsvpResponse
  Comment comment
  number additionalNumberOfGuests

}
