classDiagram
  SingleFamilyResidence -- QuantitativeValue,number
SingleFamilyResidence -- QuantitativeValue


House <|-- SingleFamilyResidence
class SingleFamilyResidence {

  QuantitativeValue,number numberOfRooms
  QuantitativeValue occupancy

}
