classDiagram
  SoftwareApplication -- CreativeWork
  SoftwareApplication -- SoftwareApplication
  SoftwareApplication -- ImageObject
  SoftwareApplication -- DataFeed


class SoftwareApplication {

  string countriesSupported
  string installUrl
  string operatingSystem
  string memoryRequirements
  string memoryRequirements
  string softwareVersion
  string storageRequirements
  string storageRequirements
  CreativeWork softwareHelp
  string applicationSubCategory
  string applicationSubCategory
  string downloadUrl
  string applicationCategory
  string applicationCategory
  string countriesNotSupported
  string softwareRequirements
  string softwareRequirements
  SoftwareApplication softwareAddOn
  string applicationSuite
  string requirements
  string requirements
  string permissions
  string processorRequirements
  ImageObject screenshot
  string screenshot
  string featureList
  string featureList
  string releaseNotes
  string releaseNotes
  DataFeed supportingData
  string fileSize
  string device
  string availableOnDevice

 }
