classDiagram
  SportsEvent -- Person
  SportsEvent -- SportsTeam


class SportsEvent {

  Person homeTeam
  SportsTeam homeTeam
  SportsTeam awayTeam
  Person awayTeam
  Person competitor
  SportsTeam competitor
  string sport
  string sport

 }
