classDiagram
  SteeringPositionValue -- schema:SteeringPositionValue


class SteeringPositionValue {

  schema:SteeringPositionValue LeftHandDriving
  schema:SteeringPositionValue RightHandDriving

 }
