classDiagram
  SteeringPositionValue -- schema:SteeringPositionValue


QualitativeValue <|-- SteeringPositionValue
class SteeringPositionValue {

  schema:SteeringPositionValue LeftHandDriving
  schema:SteeringPositionValue RightHandDriving

}
