classDiagram
  SuperficialAnatomy -- MedicalTherapy
  SuperficialAnatomy -- AnatomicalSystem
  SuperficialAnatomy -- AnatomicalStructure
  SuperficialAnatomy -- MedicalCondition


class SuperficialAnatomy {

  MedicalTherapy relatedTherapy
  string significance
  AnatomicalSystem relatedAnatomy
  AnatomicalStructure relatedAnatomy
  MedicalCondition relatedCondition
  string associatedPathophysiology

 }
