classDiagram
  TherapeuticProcedure -- MedicalEntity
  TherapeuticProcedure -- Drug
  TherapeuticProcedure -- DoseSchedule


class TherapeuticProcedure {

  MedicalEntity adverseOutcome
  Drug drug
  DoseSchedule doseSchedule

 }
