classDiagram
  Ticket -- Seat
  Ticket -- PriceSpecification
  Ticket -- Organization
  Ticket -- date
  Ticket -- dateTime
  Ticket -- Person


class Ticket {

  string ticketToken
  string ticketToken
  Seat ticketedSeat
  PriceSpecification totalPrice
  number totalPrice
  string totalPrice
  Organization issuedBy
  string ticketNumber
  date dateIssued
  dateTime dateIssued
  string priceCurrency
  Organization underName
  Person underName

 }
