classDiagram
  TouristAttraction -- Audience
  TouristAttraction -- Language


class TouristAttraction {

  Audience touristType
  string touristType
  string availableLanguage
  Language availableLanguage

 }
