classDiagram
  TouristDestination -- Audience
  TouristDestination -- TouristAttraction


class TouristDestination {

  Audience touristType
  string touristType
  TouristAttraction includesAttraction

 }
