classDiagram
  TrainTrip -- TrainStation


Trip <|-- TrainTrip
class TrainTrip {

  string trainName
  TrainStation departureStation
  string departurePlatform
  string trainNumber
  string arrivalPlatform
  TrainStation arrivalStation

}
