classDiagram
  TVEpisode -- Country
  TVEpisode -- Language
  TVEpisode -- TVSeries


class TVEpisode {

  Country countryOfOrigin
  string titleEIDR
  string titleEIDR
  Language subtitleLanguage
  string subtitleLanguage
  TVSeries partOfTVSeries

 }
