classDiagram
  TypeAndQuantityNode -- BusinessFunction
  TypeAndQuantityNode -- Product
  TypeAndQuantityNode -- Service


class TypeAndQuantityNode {

  string unitText
  BusinessFunction businessFunction
  Product typeOfGood
  Service typeOfGood
  number amountOfThisGood
  string unitCode
  string unitCode

 }
