classDiagram
  TypeAndQuantityNode -- BusinessFunction
TypeAndQuantityNode -- Product,Service
TypeAndQuantityNode -- string,string


StructuredValue <|-- TypeAndQuantityNode
class TypeAndQuantityNode {

  string unitText
  BusinessFunction businessFunction
  Product,Service typeOfGood
  number amountOfThisGood
  string,string unitCode

}
