classDiagram
  UnitPriceSpecification -- PriceTypeEnumeration
  UnitPriceSpecification -- Duration
  UnitPriceSpecification -- QuantitativeValue
  UnitPriceSpecification -- PriceComponentTypeEnumeration


class UnitPriceSpecification {

  PriceTypeEnumeration priceType
  string priceType
  string unitText
  number billingIncrement
  string unitCode
  string unitCode
  Duration billingDuration
  QuantitativeValue billingDuration
  number billingDuration
  QuantitativeValue referenceQuantity
  PriceComponentTypeEnumeration priceComponentType
  number billingStart

 }
