classDiagram
  Vein -- AnatomicalSystem,AnatomicalStructure
Vein -- AnatomicalStructure
Vein -- Vessel


Vessel <|-- Vein
class Vein {

  AnatomicalSystem,AnatomicalStructure regionDrained
  AnatomicalStructure tributary
  Vessel drainsTo

}
