classDiagram
  Vein -- AnatomicalSystem
  Vein -- AnatomicalStructure
  Vein -- Vessel


class Vein {

  AnatomicalSystem regionDrained
  AnatomicalStructure regionDrained
  AnatomicalStructure tributary
  Vessel drainsTo

 }
