classDiagram
  VideoGame -- Person
  VideoGame -- VideoObject
  VideoGame -- CreativeWork
  VideoGame -- GameServer
  VideoGame -- GamePlayMode
  VideoGame -- Thing
  VideoGame -- MusicGroup


class VideoGame {

  Person director
  Person actor
  VideoObject trailer
  string gameEdition
  CreativeWork cheatCode
  GameServer gameServer
  CreativeWork gameTip
  Person actors
  GamePlayMode playMode
  string gamePlatform
  string gamePlatform
  Thing gamePlatform
  Person musicBy
  MusicGroup musicBy
  Person directors

 }
