classDiagram
  VideoObject -- Person
  VideoObject -- MediaObject
  VideoObject -- ImageObject
  VideoObject -- MusicGroup


class VideoObject {

  string embeddedTextCaption
  Person director
  Person actor
  string caption
  MediaObject caption
  ImageObject thumbnail
  string transcript
  string videoQuality
  string videoFrameSize
  Person actors
  Person musicBy
  MusicGroup musicBy
  Person directors

 }
