classDiagram
  WarrantyPromise -- WarrantyScope
WarrantyPromise -- QuantitativeValue


StructuredValue <|-- WarrantyPromise
class WarrantyPromise {

  WarrantyScope warrantyScope
  QuantitativeValue durationOfWarranty

}
