classDiagram
SizeGroupEnumeration o-- WearableSizeGroupEnumeration
  class WearableSizeGroupEnumeration {
<<enumeration>>
  o WearableSizeGroupShort
  o WearableSizeGroupExtraTall
  o WearableSizeGroupMaternity
  o WearableSizeGroupWomens
  o . . . 13 more values
}
