classDiagram
  WorkBasedProgram -- MonetaryAmountDistribution
  WorkBasedProgram -- CategoryCode


class WorkBasedProgram {

  MonetaryAmountDistribution trainingSalary
  CategoryCode occupationalCategory
  string occupationalCategory

 }
