import { Product } from "./Product";
import { AdultOrientedEnumeration } from "./AdultOrientedEnumeration";
import { string,string,Product } from "./string,string,Product";
import { Review } from "./Review";
import { QuantitativeValue,Distance } from "./QuantitativeValue,Distance";
import { Country } from "./Country";
import { DefinedTerm,string } from "./DefinedTerm,string";
import { string,string,PhysicalActivityCategory,Thing,CategoryCode } from "./string,string,PhysicalActivityCategory,Thing,CategoryCode";
import { Grant } from "./Grant";
import { Distance,QuantitativeValue } from "./Distance,QuantitativeValue";
import { DefinedTerm,string,string } from "./DefinedTerm,string,string";
import { date } from "./date";
import { EnergyConsumptionDetails } from "./EnergyConsumptionDetails";
import { Audience } from "./Audience";
import { Offer,Demand } from "./Offer,Demand";
import { OfferItemCondition } from "./OfferItemCondition";
import { AggregateRating } from "./AggregateRating";
import { Service,Product } from "./Service,Product";
import { ProductModel,ProductGroup } from "./ProductModel,ProductGroup";
import { Organization,Brand } from "./Organization,Brand";
import { Organization } from "./Organization";
import { QuantitativeValue } from "./QuantitativeValue";
import { string,ImageObject } from "./string,ImageObject";
import { ProductModel,string } from "./ProductModel,string";
import { MerchantReturnPolicy } from "./MerchantReturnPolicy";
import { QuantitativeValue,DefinedTerm,string,SizeSpecification } from "./QuantitativeValue,DefinedTerm,string,SizeSpecification";
import { PropertyValue } from "./PropertyValue";


export class Product extends Thing {
  isAccessoryOrSparePartFor: Product;
  hasAdultConsideration: AdultOrientedEnumeration;
  gtin12: string;
  nsn: string;
  material: string,string,Product;
  review: Review;
  award: string;
  width: QuantitativeValue,Distance;
  countryOfOrigin: Country;
  pattern: DefinedTerm,string;
  category: string,string,PhysicalActivityCategory,Thing,CategoryCode;
  funding: Grant;
  mpn: string;
  height: Distance,QuantitativeValue;
  keywords: DefinedTerm,string,string;
  purchaseDate: date;
  hasEnergyConsumptionDetails: EnergyConsumptionDetails;
  audience: Audience;
  offers: Offer,Demand;
  productionDate: date;
  itemCondition: OfferItemCondition;
  awards: string;
  gtin: string;
  productID: string;
  countryOfAssembly: string;
  color: string;
  aggregateRating: AggregateRating;
  isSimilarTo: Service,Product;
  depth: Distance,QuantitativeValue;
  countryOfLastProcessing: string;
  isVariantOf: ProductModel,ProductGroup;
  slogan: string;
  brand: Organization,Brand;
  manufacturer: Organization;
  hasMeasurement: QuantitativeValue;
  isConsumableFor: Product;
  logo: string,ImageObject;
  gtin8: string;
  sku: string;
  inProductGroupWithID: string;
  model: ProductModel,string;
  hasMerchantReturnPolicy: MerchantReturnPolicy;
  releaseDate: date;
  gtin14: string;
  weight: QuantitativeValue;
  size: QuantitativeValue,DefinedTerm,string,SizeSpecification;
  additionalProperty: PropertyValue;
  gtin13: string;
  reviews: Review;
  isFamilyFriendly: boolean;
  isRelatedTo: Service,Product;


}
